

#define USE_SENTINEL 1

typedef enum {
  IFAT_UINT8=1,    // IFAT = Info flow arg type
  IFAT_UINT16=2,
  IFAT_UINT32=3,
  IFAT_UINT64=4, 
  IFAT_STRING=5,
} info_flow_op_arg_type_enum_t;


typedef struct info_flow_op_arg_struct_t {
  info_flow_op_arg_type_enum_t type;   // tags the union
  union {
    uint8_t u8;        // unsigned ints of various sizes
    uint16_t u16;
    uint32_t u32;
    uint64_t u64;
    char *str          // a string
  } val
} info_flow_op_arg_t;



typedef struct info_flow_op_struct_t {
  info_flow_op_enum_t num;     // the number of the op
  info_flow_op_arg_t arg[12];  // up to 12 arguments
  uint32_t num_args;          // number of arguments 
} Info_flow_op_t;

/*
  '0' means 0 bytes, i.e. no args for this op
  '1' means 1 byte, i.e. uint8_t
  '2' means 2 bytes, i.e. uint16_t
  '4' means 4 bytes, i.e. uint32_t
  '8' means 8 bytes, i.e. uint64_t
  's' means a string
*/


char *info_flow_log_format[] = { 
  "", // AAA
  "", // AAD
  "", // AAM,
  "", // AAS
  "", // ADDL_A0_AL
  "", // ADDL_A0_IM
  "", // ADDL_A0_SS
  "", // ADDL_EDI_T0
  "", // ADDL_ESI_T0
  "", // ADDL_ESP_2
  "", // ADDL_ESP_4
  "", // ADDL_ESP_IM
  "", // ADDL_T0_IM
  "", // ADDL_T0_T1
  "", // ADDL_T1_IM
ADDR_ADDL_A0_SEG
	"8" // ADDR_MOVL_A0_SEG
ADDR_MOVL_ENV_T0
ADDR_MOVL_ENV_T1
ADDR_MOVL_T0_ENV
ADDR_MOVTL_ENV_T0
ADDR_MOVTL_ENV_T1
ADDR_MOVTL_T0_ENV
ADDR_MOVTL_T1_ENV
ADDW_EDI_T0
ADDW_ESI_T0
ADDW_ESP_2
ADDW_ESP_4
ADDW_ESP_IM
ANDL_A0_FFFF
ANDL_T0_FFFF
ANDL_T0_IM
ANDL_T0_T1
ARPL
BSWAPL_T0
CLTS
CMPXCHG8B_PART1
CMPXCHG8B_PART2
CPUID
  "", // DAA
DAS
DECL_ECX
DECL_T0
DECW_ECX
DIVB_AL_T0
DIVL_EAX_T0
DIVW_AX_T0
ENTER_LEVEL
FNSTSW_EAX
IDIVB_AL_T0
IDIVL_EAX_T0
IDIVW_AX_T0
IMULB_AL_T0
IMULL_EAX_T0
IMULL_T0_T1
IMULW_AX_T0
IMULW_T0_T1
INCL_T0
INVLPG_A0
IRET_PROTECTED
IRET_REAL
JMP_T0
LAR
LCALL_PROTECTED_T0_T1
LCALL_REAL_T0_T1
LJMP_PROTECTED_T0_T1
LLDT_T0
LMSW_T0
LRET_PROTECTED
LSL
LTR_T0
MEMSUFFIX_ADDR_LDL_T0_A0
MEMSUFFIX_ADDR_LDL_T1_A0
MEMSUFFIX_ADDR_LDSB_T0_A0
MEMSUFFIX_ADDR_LDSB_T1_A0
MEMSUFFIX_ADDR_LDSW_T0_A0
MEMSUFFIX_ADDR_LDSW_T1_A0
MEMSUFFIX_ADDR_LDUB_T0_A0
MEMSUFFIX_ADDR_LDUB_T1_A0
MEMSUFFIX_ADDR_LDUW_T0_A0
MEMSUFFIX_ADDR_LDUW_T1_A0
MEMSUFFIX_ADDR_STB_T0_A0
MEMSUFFIX_ADDR_STL_T0_A0
MEMSUFFIX_ADDR_STL_T1_A0
MEMSUFFIX_ADDR_STW_T0_A0
MEMSUFFIX_ADDR_STW_T1_A0
MOVB_EFLAGS_T0
MOVL_A0_IM
MOVL_CRN_T0
MOVL_DRN_T0
MOVL_EFLAGS_T0
MOVL_EFLAGS_T0_CPL0
MOVL_EFLAGS_T0_IO
MOVL_EIP_IM
MOVL_SEG_T0
MOVL_SEG_T0_VM
MOVL_T0_0
MOVL_T0_EFLAGS
MOVL_T0_IM
MOVL_T0_IMU
MOVL_T0_SEG
MOVL_T0_T1
MOVL_T1_A0
MOVL_T1_IM
MOVL_T1_IMU
MOVSBL_T0_T0
MOVSBW_AX_AL
MOVSLQ_EDX_EAX
MOVSWL_DX_AX
MOVSWL_EAX_AX
MOVSWL_T0_T0
MOVTL_T0_CR8
MOVW_EFLAGS_T0
MOVW_EFLAGS_T0_CPL0
MOVW_EFLAGS_T0_IO
MOVZBL_T0_T0
MOVZWL_T0_T0
MOV_T0_CC
MULB_AL_T0
MULL_EAX_T0
MULW_AX_T0
NEGL_T0
NOTL_T0
ORL_T0_T1
RDMSR
RDTSC
REG_ADDL_A0_R
REG_ADDL_A0_R_S1
REG_ADDL_A0_R_S2
REG_ADDL_A0_R_S3
REG_CMOVL_R_T1_T0
REG_CMOVW_R_T1_T0
REG_MOVB_R_T0
REG_MOVB_R_T1
REG_MOVH_R_T0
REG_MOVH_R_T1
REG_MOVH_T0_R
REG_MOVH_T1_R
REG_MOVL_A0_R
REG_MOVL_R_A0
REG_MOVL_R_T0
REG_MOVL_R_T1
REG_MOVL_T0_R
REG_MOVL_T1_R
REG_MOVW_R_A0
REG_MOVW_R_T0
REG_MOVW_R_T1
SALC
SETBE_T0_CC
SETB_T0_CC
SETLE_T0_CC
SETL_T0_CC
SETO_T0_CC
SETP_T0_CC
SETS_T0_CC
SETZ_T0_CC
SHIFT_ADD_BIT_A0_T1
SHIFT_BSF_T0_CC
SHIFT_BSR_T0_CC
SHIFT_BTC_T0_T1_CC
SHIFT_BTR_T0_T1_CC
SHIFT_BTS_T0_T1_CC
SHIFT_IN_DX_T0
SHIFT_IN_T0_T1
SHIFT_MEM_WRITE_ADC_T0_T1_CC
SHIFT_MEM_WRITE_CMPXCHG_T0_T1_EAX_CC
SHIFT_MEM_WRITE_RCL_T0_T1_CC
SHIFT_MEM_WRITE_RCR_T0_T1_CC
SHIFT_MEM_WRITE_ROL_T0_T1
SHIFT_MEM_WRITE_ROL_T0_T1_CC
SHIFT_MEM_WRITE_ROR_T0_T1
SHIFT_MEM_WRITE_ROR_T0_T1_CC
SHIFT_MEM_WRITE_SAR_T0_T1_CC
SHIFT_MEM_WRITE_SBB_T0_T1_CC
SHIFT_MEM_WRITE_SHLD_T0_T1_ECX_CC
SHIFT_MEM_WRITE_SHLD_T0_T1_IM_CC
SHIFT_MEM_WRITE_SHL_T0_T1_CC
SHIFT_MEM_WRITE_SHRD_T0_T1_ECX_CC
SHIFT_MEM_WRITE_SHRD_T0_T1_IM_CC
SHIFT_MEM_WRITE_SHR_T0_T1_CC
SHIFT_MOVL_T0_DSHIFT
SHIFT_SAR_T0_T1
SHIFT_SETBE_T0_SUB
SHIFT_SETB_T0_SUB
SHIFT_SETLE_T0_SUB
SHIFT_SETL_T0_SUB
SHIFT_SETS_T0_SUB
SHIFT_SETZ_T0_SUB
SHIFT_SHL_T0_T1
SHIFT_SHR_T0_T1
SUBL_A0_2
SUBL_A0_4
SUBL_T0_T1
SYSENTER
SYSEXIT
WRMSR
XORL_T0_T1
XOR_T0_1
KEYBOARD_INPUT
NEW_KEYBOARD_LABEL
NEW_NETWORK_LABEL
NETWORK_INPUT_BYTE_T0
NETWORK_INPUT_WORD_T0
NETWORK_INPUT_LONG_T0
NETWORK_INPUT_BYTE_T1
NETWORK_INPUT_WORD_T1
NETWORK_INPUT_LONG_T1
NETWORK_OUTPUT_BYTE_T0
NETWORK_OUTPUT_WORD_T0
NETWORK_OUTPUT_LONG_T0
NETWORK_OUTPUT_BYTE_T1
NETWORK_OUTPUT_WORD_T1
NETWORK_OUTPUT_LONG_T1
HD_TRANSFER
	"8",  // HD_TRANSFER_PART1,
	"84", // HD_TRANSFER_PART2,
MMU_PHYS_ADDR_DIRECT_LDQ
MMU_PHYS_ADDR_DIRECT_LDL
MMU_PHYS_ADDR_DIRECT_LDW
MMU_PHYS_ADDR_DIRECT_LDB
MMU_PHYS_ADDR_IO_ALIGNED_LDQ
MMU_PHYS_ADDR_IO_ALIGNED_LDL
MMU_PHYS_ADDR_IO_ALIGNED_LDW
MMU_PHYS_ADDR_IO_ALIGNED_LDB
MMU_PHYS_ADDR_UNALIGNED_SAME_PAGE_LDQ
MMU_PHYS_ADDR_UNALIGNED_SAME_PAGE_LDL
MMU_PHYS_ADDR_UNALIGNED_SAME_PAGE_LDB
MMU_PHYS_ADDR_UNALIGNED_SAME_PAGE_LDW
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART1_LDQ
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART1_LDL
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART1_LDW
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART1_LDB
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART2_LDQ
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART2_LDL
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART2_LDB
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART2_LDW
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_IO_PART2_LDQ
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_IO_PART2_LDL
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_IO_PART2_LDB
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_IO_PART2_LDW
MMU_PHYS_ADDR_DIRECT_STQ
MMU_PHYS_ADDR_DIRECT_STL
MMU_PHYS_ADDR_DIRECT_STW
MMU_PHYS_ADDR_DIRECT_STB
MMU_PHYS_ADDR_IO_ALIGNED_STQ
MMU_PHYS_ADDR_IO_ALIGNED_STL
MMU_PHYS_ADDR_IO_ALIGNED_STW
MMU_PHYS_ADDR_IO_ALIGNED_STB
MMU_PHYS_ADDR_UNALIGNED_SAME_PAGE_STQ
MMU_PHYS_ADDR_UNALIGNED_SAME_PAGE_STL
MMU_PHYS_ADDR_UNALIGNED_SAME_PAGE_STB
MMU_PHYS_ADDR_UNALIGNED_SAME_PAGE_STW
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART1_STQ
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART1_STL
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART1_STW
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART1_STB
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART2_STQ
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART2_STL
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART2_STB
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_PART2_STW
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_IO_PART2_STQ
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_IO_PART2_STL
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_IO_PART2_STB
MMU_PHYS_ADDR_UNALIGNED_DIFFERENT_PAGE_IO_PART2_STW
X86_INSN
CMPXCHG_T0_T1_EAX_CC_CASE1
CMPXCHG_T0_T1_EAX_CC_CASE2
CMPXCHG_T0_T1_EAX_CC_CASE3
SAVE_REG
RESTORE_REG
CPU_READ_ADDR
CPU_WRITE_ADDR
TLB_FILL
SAVE_ENV
RESTORE_ENV
WRITE_CURRENT_PID
WRITE_CURRENT_UID
SET_CPL

// starting here from # 277 
// system calls 
// NB: autogenerated from 
// /usr/include/asm/unistd_32.h
// linux kernel 
// Linux snowy 2.6.27-9-generic #1 SMP Thu Nov 20 21:57:00 UTC 2008 i686 GNU/Linux
SYS_RESTART_SYSCALL    // 0 
SYS_EXIT    // 1 
SYS_FORK    // 2 
SYS_READ    // 3 
SYS_WRITE    // 4 
SYS_OPEN    // 5 
SYS_CLOSE    // 6 
SYS_WAITPID    // 7 
SYS_CREAT    // 8 
SYS_LINK    // 9 
SYS_UNLINK    // 10 
SYS_EXECVE    // 11 
SYS_CHDIR    // 12 
SYS_TIME    // 13 
SYS_MKNOD    // 14 
SYS_CHMOD    // 15 
SYS_LCHOWN    // 16 
SYS_BREAK    // 17 
SYS_OLDSTAT    // 18 
SYS_LSEEK    // 19 
SYS_GETPID    // 20 
SYS_MOUNT    // 21 
SYS_UMOUNT    // 22 
SYS_SETUID    // 23 
SYS_GETUID    // 24 
SYS_STIME    // 25 
SYS_PTRACE    // 26 
SYS_ALARM    // 27 
SYS_OLDFSTAT    // 28 
SYS_PAUSE    // 29 
SYS_UTIME    // 30 
SYS_STTY    // 31 
SYS_GTTY    // 32 
SYS_ACCESS    // 33 
SYS_NICE    // 34 
SYS_FTIME    // 35 
SYS_SYNC    // 36 
SYS_KILL    // 37 
SYS_RENAME    // 38 
SYS_MKDIR    // 39 
SYS_RMDIR    // 40 
SYS_DUP    // 41 
SYS_PIPE    // 42 
SYS_TIMES    // 43 
SYS_PROF    // 44 
SYS_BRK    // 45 
SYS_SETGID    // 46 
SYS_GETGID    // 47 
SYS_SIGNAL    // 48 
SYS_GETEUID    // 49 
SYS_GETEGID    // 50 
SYS_ACCT    // 51 
SYS_UMOUNT2    // 52 
SYS_LOCK    // 53 
SYS_IOCTL    // 54 
SYS_FCNTL    // 55 
SYS_MPX    // 56 
SYS_SETPGID    // 57 
SYS_ULIMIT    // 58 
SYS_OLDOLDUNAME    // 59 
SYS_UMASK    // 60 
SYS_CHROOT    // 61 
SYS_USTAT    // 62 
SYS_DUP2    // 63 
SYS_GETPPID    // 64 
SYS_GETPGRP    // 65 
SYS_SETSID    // 66 
SYS_SIGACTION    // 67 
SYS_SGETMASK    // 68 
SYS_SSETMASK    // 69 
SYS_SETREUID    // 70 
SYS_SETREGID    // 71 
SYS_SIGSUSPEND    // 72 
SYS_SIGPENDING    // 73 
SYS_SETHOSTNAME    // 74 
SYS_SETRLIMIT    // 75 
SYS_GETRLIMIT    // 76 
SYS_GETRUSAGE    // 77 
SYS_GETTIMEOFDAY    // 78 
SYS_SETTIMEOFDAY    // 79 
SYS_GETGROUPS    // 80 
SYS_SETGROUPS    // 81 
SYS_SELECT    // 82 
SYS_SYMLINK    // 83 
SYS_OLDLSTAT    // 84 
SYS_READLINK    // 85 
SYS_USELIB    // 86 
SYS_SWAPON    // 87 
SYS_REBOOT    // 88 
SYS_READDIR    // 89 
SYS_MMAP    // 90 
SYS_MUNMAP    // 91 
SYS_TRUNCATE    // 92 
SYS_FTRUNCATE    // 93 
SYS_FCHMOD    // 94 
SYS_FCHOWN    // 95 
SYS_GETPRIORITY    // 96 
SYS_SETPRIORITY    // 97 
SYS_PROFIL    // 98 
SYS_STATFS    // 99 
SYS_FSTATFS    // 100 
SYS_IOPERM    // 101 
SYS_SOCKETCALL    // 102 
SYS_SYSLOG    // 103 
SYS_SETITIMER    // 104 
SYS_GETITIMER    // 105 
SYS_STAT    // 106 
SYS_LSTAT    // 107 
SYS_FSTAT    // 108 
SYS_OLDUNAME    // 109 
SYS_IOPL    // 110 
SYS_VHANGUP    // 111 
SYS_IDLE    // 112 
SYS_VM86OLD    // 113 
SYS_WAIT4    // 114 
SYS_SWAPOFF    // 115 
SYS_SYSINFO    // 116 
SYS_IPC    // 117 
SYS_FSYNC    // 118 
SYS_SIGRETURN    // 119 
SYS_CLONE    // 120 
SYS_SETDOMAINNAME    // 121 
SYS_UNAME    // 122 
SYS_MODIFY_LDT    // 123 
SYS_ADJTIMEX    // 124 
SYS_MPROTECT    // 125 
SYS_SIGPROCMASK    // 126 
SYS_CREATE_MODULE    // 127 
SYS_INIT_MODULE    // 128 
SYS_DELETE_MODULE    // 129 
SYS_GET_KERNEL_SYMS    // 130 
SYS_QUOTACTL    // 131 
SYS_GETPGID    // 132 
SYS_FCHDIR    // 133 
SYS_BDFLUSH    // 134 
SYS_SYSFS    // 135 
SYS_PERSONALITY    // 136 
SYS_AFS_SYSCALL    // 137 
SYS_SETFSUID    // 138 
SYS_SETFSGID    // 139 
SYS__LLSEEK    // 140 
SYS_GETDENTS    // 141 
SYS__NEWSELECT    // 142 
SYS_FLOCK    // 143 
SYS_MSYNC    // 144 
SYS_READV    // 145 
SYS_WRITEV    // 146 
SYS_GETSID    // 147 
SYS_FDATASYNC    // 148 
SYS__SYSCTL    // 149 
SYS_MLOCK    // 150 
SYS_MUNLOCK    // 151 
SYS_MLOCKALL    // 152 
SYS_MUNLOCKALL    // 153 
SYS_SCHED_SETPARAM    // 154 
SYS_SCHED_GETPARAM    // 155 
SYS_SCHED_SETSCHEDULER    // 156 
SYS_SCHED_GETSCHEDULER    // 157 
SYS_SCHED_YIELD    // 158 
SYS_SCHED_GET_PRIORITY_MAX    // 159 
SYS_SCHED_GET_PRIORITY_MIN    // 160 
SYS_SCHED_RR_GET_INTERVAL    // 161 
SYS_NANOSLEEP    // 162 
SYS_MREMAP    // 163 
SYS_SETRESUID    // 164 
SYS_GETRESUID    // 165 
SYS_VM86    // 166 
SYS_QUERY_MODULE    // 167 
SYS_POLL    // 168 
SYS_NFSSERVCTL    // 169 
SYS_SETRESGID    // 170 
SYS_GETRESGID    // 171 
SYS_PRCTL    // 172 
SYS_RT_SIGRETURN    // 173 
SYS_RT_SIGACTION    // 174 
SYS_RT_SIGPROCMASK    // 175 
SYS_RT_SIGPENDING    // 176 
SYS_RT_SIGTIMEDWAIT    // 177 
SYS_RT_SIGQUEUEINFO    // 178 
SYS_RT_SIGSUSPEND    // 179 
SYS_PREAD64    // 180 
SYS_PWRITE64    // 181 
SYS_CHOWN    // 182 
SYS_GETCWD    // 183 
SYS_CAPGET    // 184 
SYS_CAPSET    // 185 
SYS_SIGALTSTACK    // 186 
SYS_SENDFILE    // 187 
SYS_GETPMSG    // 188 
SYS_PUTPMSG    // 189 
SYS_VFORK    // 190 
SYS_UGETRLIMIT    // 191 
SYS_MMAP2    // 192 
SYS_TRUNCATE64    // 193 
SYS_FTRUNCATE64    // 194 
SYS_STAT64    // 195 
SYS_LSTAT64    // 196 
SYS_FSTAT64    // 197 
SYS_LCHOWN32    // 198 
SYS_GETUID32    // 199 
SYS_GETGID32    // 200 
SYS_GETEUID32    // 201 
SYS_GETEGID32    // 202 
SYS_SETREUID32    // 203 
SYS_SETREGID32    // 204 
SYS_GETGROUPS32    // 205 
SYS_SETGROUPS32    // 206 
SYS_FCHOWN32    // 207 
SYS_SETRESUID32    // 208 
SYS_GETRESUID32    // 209 
SYS_SETRESGID32    // 210 
SYS_GETRESGID32    // 211 
SYS_CHOWN32    // 212 
SYS_SETUID32    // 213 
SYS_SETGID32    // 214 
SYS_SETFSUID32    // 215 
SYS_SETFSGID32    // 216 
SYS_PIVOT_ROOT    // 217 
SYS_MINCORE    // 218 
SYS_MADVISE    // 219 
SYS_MADVISE1    // 219 
SYS_GETDENTS64    // 220 
SYS_FCNTL64    // 221 
SYS_GETTID    // 224 
SYS_READAHEAD    // 225 
SYS_SETXATTR    // 226 
SYS_LSETXATTR    // 227 
SYS_FSETXATTR    // 228 
SYS_GETXATTR    // 229 
SYS_LGETXATTR    // 230 
SYS_FGETXATTR    // 231 
SYS_LISTXATTR    // 232 
SYS_LLISTXATTR    // 233 
SYS_FLISTXATTR    // 234 
SYS_REMOVEXATTR    // 235 
SYS_LREMOVEXATTR    // 236 
SYS_FREMOVEXATTR    // 237 
SYS_TKILL    // 238 
SYS_SENDFILE64    // 239 
SYS_FUTEX    // 240 
SYS_SCHED_SETAFFINITY    // 241 
SYS_SCHED_GETAFFINITY    // 242 
SYS_SET_THREAD_AREA    // 243 
SYS_GET_THREAD_AREA    // 244 
SYS_IO_SETUP    // 245 
SYS_IO_DESTROY    // 246 
SYS_IO_GETEVENTS    // 247 
SYS_IO_SUBMIT    // 248 
SYS_IO_CANCEL    // 249 
SYS_FADVISE64    // 250 
SYS_EXIT_GROUP    // 252 
SYS_LOOKUP_DCOOKIE    // 253 
SYS_EPOLL_CREATE    // 254 
SYS_EPOLL_CTL    // 255 
SYS_EPOLL_WAIT    // 256 
SYS_REMAP_FILE_PAGES    // 257 
SYS_SET_TID_ADDRESS    // 258 
SYS_TIMER_CREATE    // 259 
SYS_TIMER_SETTIME // 260
SYS_TIMER_GETTIME  // 261
SYS_TIMER_GETOVERRUN // 262
SYS_TIMER_DELETE // 263
SYS_CLOCK_SETTIME  // 264
SYS_CLOCK_GETTIME // 265
SYS_CLOCK_GETRES // 266
SYS_CLOCK_NANOSLEEP // 267
SYS_STATFS64    // 268 
SYS_FSTATFS64    // 269 
SYS_TGKILL    // 270 
SYS_UTIMES    // 271 
SYS_FADVISE64_64    // 272 
SYS_VSERVER    // 273 
SYS_MBIND    // 274 
SYS_GET_MEMPOLICY    // 275 
SYS_SET_MEMPOLICY    // 276 
SYS_MQ_OPEN    // 277 
SYS_MQ_UNLINK // 278
SYS_MQ_TIMEDSEND // 279
SYS_MQ_TIMEDRECEIVE  // 280
SYS_MQ_NOTIFY // 281
SYS_MQ_GETSETATTR // 282
SYS_KEXEC_LOAD    // 283 
SYS_WAITID    // 284 
SYS_SETALTROOT // 285
SYS_ADD_KEY    // 286 
SYS_REQUEST_KEY    // 287 
SYS_KEYCTL    // 288 
SYS_IOPRIO_SET    // 289 
SYS_IOPRIO_GET    // 290 
SYS_INOTIFY_INIT    // 291 
SYS_INOTIFY_ADD_WATCH    // 292 
SYS_INOTIFY_RM_WATCH    // 293 
SYS_MIGRATE_PAGES    // 294 
SYS_OPENAT    // 295 
SYS_MKDIRAT    // 296 
SYS_MKNODAT    // 297 
SYS_FCHOWNAT    // 298 
SYS_FUTIMESAT    // 299 
SYS_FSTATAT64    // 300 
SYS_UNLINKAT    // 301 
SYS_RENAMEAT    // 302 
SYS_LINKAT    // 303 
SYS_SYMLINKAT    // 304 
SYS_READLINKAT    // 305 
SYS_FCHMODAT    // 306 
SYS_FACCESSAT    // 307 
SYS_PSELECT6    // 308 
SYS_PPOLL    // 309 
SYS_UNSHARE    // 310 
SYS_SET_ROBUST_LIST    // 311 
SYS_GET_ROBUST_LIST    // 312 
SYS_SPLICE    // 313 
SYS_SYNC_FILE_RANGE    // 314 
SYS_TEE    // 315 
SYS_VMSPLICE    // 316 
SYS_MOVE_PAGES    // 317 
SYS_GETCPU    // 318 
SYS_EPOLL_PWAIT    // 319 
SYS_UTIMENSAT    // 320 
SYS_SIGNALFD    // 321 
SYS_TIMERFD_CREATE    // 322 
SYS_EVENTFD    // 323 
SYS_FALLOCATE    // 324 
SYS_TIMERFD_SETTIME    // 325 
SYS_TIMERFD_GETTIME    // 326 
SYS_SIGNALFD4    // 327 
SYS_EVENTFD2    // 328 
SYS_EPOLL_CREATE1    // 329 
SYS_DUP3    // 330 
SYS_PIPE2    // 331 
SYS_INOTIFY_INIT1    // 332 
SYS_UNKNOWN // ?
SYS_IRET_OR_SYSEXIT 

PID_CHANGE
UID_CHANGE,


info_flow_log_write(INFO_FLOW_LOG_OP_AAA);

info_flow_log_write(IFLO_MOVL_A0,REGNUM);
info_flow_log_read(INFO_FLOW_LOG_OP_MOVL_A0,&regnum);

