// NB: This code is auto-generated by make_iferret_code.pl. 
// It's job is to generate the big array of strings specifying the 
// format of iferret log entries for system calls.

char *iferret_log_format[] = {
  "", // 0 long sys_restart_syscall(void);
  "i", // 1 long sys_exit(int error_code);
  "", // 2 pid_t fork(void);
  "isi", // 3 ssize_t sys_read(unsigned int fd, char __user *buf, size_t count);
  "isi", // 4 ssize_t sys_write(unsigned int fd, const char __user *buf, size_t count);
  "sii", // 5 long sys_open(const char __user *filename, int flags, int mode);
  "i", // 6 long sys_close(unsigned int fd);
  "iii", // 7 long sys_waitpid(pid_t pid, int __user *stat_addr, int options);
  "si", // 8 long sys_creat(const char __user *pathname, int mode);    
  "ss", // 9 long sys_link(const char __user *oldname, const char __user *newname);
  "s", // 10 long sys_unlink(const char __user *pathname);
  "iii", // 11 int execve(const char *filename, char *const argv[], char *const envp[]);
  "s", // 12 long sys_chdir(const char __user *filename);
  "i", // 13 long sys_time(time_t __user *tloc);
  "sii", // 14 long sys_mknod(const char __user *filename, int mode, unsigned dev);
  "si", // 15 long sys_chmod(const char __user *filename, mode_t mode);
  "si", // 16 long sys_lchown(const char __user *filename, unsigned dev);
  "", // 17 missing sys_break
  "ii", // 18 int stat(const char *path, struct stat *buf);
  "iii", // 19 off_t sys_lseek(unsigned int fd, off_t offset, unsigned int origin);
  "", // 20 long sys_getpid(void);
  "sssii", // 21 long sys_mount(char __user *dev_name, char __user *dir_name, char __user *type, unsigned long flags, void __user *data);
  "si", // 22 long sys_umount(char __user *name, int flags);
  "i", // 23 long sys_setuid(uid_t uid);
  "", // 24 long sys_getuid(void);
  "i", // 25 long sys_stime(time_t __user *tptr);
  "iiii", // 26 long sys_ptrace(long request, long pid, long addr, long data);
  "i", // 27 unsigned long sys_alarm(unsigned int seconds);
  "", // 28 missing sys_oldfstat 
  "", // 29 long sys_pause(void);
  "si", // 30 long sys_utime(char __user *filename, struct utimbuf __user *times);
  "", // 31 missing sys_stty
  "", // 32 missing sys_gtty
  "si", // 33 long sys_access(const char __user *filename, int mode);
  "i", // 34 long sys_nice(int increment);
  "", // 35 missing sys_ftime 
  "", // 36 long sys_sync(void);
  "ii", // 37 long sys_kill(int pid, int sig);
  "ss", // 38 long sys_rename(const char __user *oldname, const char __user *newname);
  "si", // 39 long sys_mkdir(const char __user *pathname, int mode);
  "s", // 40 long sys_rmdir(const char __user *pathname);
  "i", // 41 long sys_dup(unsigned int fildes);
  "i", // 42 int pipe(int pipefd[2]);
  "i", // 43 long sys_times(struct tms __user *tbuf);
  "", // 44 missing sys_prof
  "i", // 45 unsigned long sys_brk(unsigned long brk);
  "i", // 46 long sys_setgid(gid_t gid);
  "", // 47 long sys_getgid(void);
  "ii", // 48 unsigned long sys_signal(int sig, __sighandler_t handler);
  "", // 49 long sys_geteuid(void);
  "", // 50 long sys_getegid(void);
  "s", // 51 long sys_acct(const char __user *name);
  "ii", // 52 int umount2(const char *target, int flags);
  "", // 53 missing sys_lock
  "iii", // 54 long sys_ioctl(unsigned int fd, unsigned int cmd, unsigned long arg);
  "iii", // 55 long sys_fcntl(unsigned int fd, unsigned int cmd, unsigned long arg);
  "", // 56 missing sys_mpx 
  "ii", // 57 long sys_setpgid(pid_t pid, pid_t pgid);    
  "", // 58 missing sys_ulimit
  "", // 59 missing sys_oldolduname 
  "i", // 60 long sys_umask(int mask);
  "s", // 61 long sys_chroot(const char __user *filename);
  "ii", // 62 long sys_ustat(unsigned dev, struct ustat __user *ubuf);
  "ii", // 63 long sys_dup2(unsigned int oldfd, unsigned int newfd);
  "", // 64 long sys_getppid(void);
  "", // 65 long sys_getpgrp(void);
  "", // 66 long sys_setsid(void);
  "", // 67 missing sys_sigaction
  "", // 68 long sys_sgetmask(void);
  "i", // 69 long sys_ssetmask(int newmask);
  "ii", // 70 long sys_setreuid(uid_t ruid, uid_t euid);
  "ii", // 71 long sys_setregid(gid_t rgid, gid_t egid);
  "", // 72 missing sys_sigsuspend
  "i", // 73 long sys_sigpending(old_sigset_t __user *set);
  "si", // 74 long sys_sethostname(char __user *name, int len);
  "ii", // 75 long sys_setrlimit(unsigned int resource, struct rlimit __user *rlim);
  "ii", // 76 long sys_getrlimit(unsigned int resource, struct rlimit __user *rlim);
  "ii", // 77 long sys_getrusage(int who, struct rusage __user *ru);
  "ii", // 78 long sys_gettimeofday(struct timeval __user *tv, struct timezone __user *tz);
  "ii", // 79 long sys_settimeofday(struct timeval __user *tv, struct timezone __user *tz);
  "ii", // 80 long sys_getgroups(int gidsetsize, gid_t __user *grouplist);
  "ii", // 81 long sys_setgroups(int gidsetsize, gid_t __user *grouplist);
  "iiiii", // 82 long sys_select(int n, fd_set __user *inp, fd_set __user *outp, fd_set __user *exp, struct timeval __user *tvp);
  "ss", // 83 long sys_symlink(const char __user *old, const char __user *new);
  "ii", // 84 int stat(const char *path, struct stat *buf);
  "ssi", // 85 long sys_readlink(const char __user *path, char __user *buf, int bufsiz);
  "s", // 86 long sys_uselib(const char __user *library);
  "si", // 87 long sys_swapon(const char __user *specialfile, int swap_flags);
  "iiii", // 88 long sys_reboot(int magic1, int magic2, unsigned int cmd, void __user *arg);    
  "iii", // 89 int readdir(unsigned int fd, struct dirent *dirp, unsigned int count);
  "iiiiii", // 90 void *mmap(void *addr, size_t length, int prot, int flags, int fd, off_t offset);
  "ii", // 91 long sys_munmap(unsigned long addr, size_t len);
  "si", // 92 long sys_truncate(const char __user *path, unsigned long length);
  "ii", // 93 long sys_ftruncate(unsigned int fd, unsigned long length);
  "ii", // 94 long sys_fchmod(unsigned int fd, mode_t mode);
  "iii", // 95 long sys_fchown(unsigned int fd, uid_t user, gid_t group);
  "ii", // 96 long sys_getpriority(int which, int who);
  "iii", // 97 long sys_setpriority(int which, int who, int niceval);
  "", // 98 missing sys_profil
  "si", // 99 long sys_statfs(const char __user * path, struct statfs __user *buf);
  "ii", // 100 long sys_fstatfs(unsigned int fd, struct statfs __user *buf);
  "iii", // 101 long sys_ioperm(unsigned long from, unsigned long num, int on);
  "ii", // 102 long sys_socketcall(int call, unsigned long __user *args);
  "isi", // 103 long sys_syslog(int type, char __user *buf, int len);
  "iii", // 104 long sys_setitimer(int which,  struct itimerval __user *value, struct itimerval __user *ovalue);
  "ii", // 105 long sys_getitimer(int which, struct itimerval __user *value);
  "si", // 106 long sys_stat(char __user *filename, struct __old_kernel_stat __user *statbuf);
  "si", // 107 long sys_lstat(char __user *filename, struct __old_kernel_stat __user *statbuf);
  "ii", // 108 long sys_fstat(unsigned int fd, struct __old_kernel_stat __user *statbuf);
  "i", // 109 int uname(struct utsname *buf);
  "i", // 110 int iopl(int level);
  "", // 111 long sys_vhangup(void);
  "", // 112 int idle(void);
  "i", // 113 int vm86old(struct vm86_struct *info);
  "iiii", // 114 long sys_wait4(pid_t pid, int __user *stat_addr, int options, struct rusage __user *ru);
  "s", // 115 long sys_swapoff(const char __user *specialfile);
  "i", // 116 long sys_sysinfo(struct sysinfo __user *info);
  "iiiiii", // 117 int ipc(unsigned int call, int first, int second, int third, void *ptr, long fifth);
  "i", // 118 long sys_fsync(unsigned int fd);
  "i", // 119 int sigreturn(unsigned long __unused);
  "iiiii", // 120 int clone(int (*fn)(void *), void *child_stack, int flags, void *arg, ...)
  "si", // 121 long sys_setdomainname(char __user *name, int len);
  "i", // 122 int uname(struct utsname *buf);
  "iii", // 123 int modify_ldt(int func, void *ptr, unsigned long bytecount);
  "i", // 124 long sys_adjtimex(struct timex __user *txc_p);
  "iii", // 125 long sys_mprotect(unsigned long start, size_t len, unsigned long prot);
  "iii", // 126 long sys_sigprocmask(int how, old_sigset_t __user *set, old_sigset_t __user *oset);
  "", // 127 missing sys_create_module 
  "iis", // 128 long sys_init_module(void __user *umod, unsigned long len, const char __user *uargs);
  "si", // 129 long sys_delete_module(const char __user *name_user, unsigned int flags);
  "", // 130 missing sys_get_kernel_syms
  "isii", // 131 long sys_quotactl(unsigned int cmd, const char __user *special, qid_t id, void __user *addr);
  "i", // 132 long sys_getpgid(pid_t pid);
  "i", // 133 long sys_fchdir(unsigned int fd);
  "ii", // 134 long sys_bdflush(int func, long data);
  "iii", // 135 long sys_sysfs(int option, unsigned long arg1, unsigned long arg2);
  "i", // 136 long sys_personality(u_long personality);
  "", // 137 missing sys_afs_syscall 
  "i", // 138 long sys_setfsuid(uid_t uid);
  "i", // 139 long sys_setfsgid(gid_t gid);
  "", // 140 missing sys__llseek
  "iii", // 141 long sys_getdents(unsigned int fd, struct linux_dirent __user *dirent, unsigned int count);
  "", // 142 missing sys__newselect 
  "ii", // 143 long sys_flock(unsigned int fd, unsigned int cmd);
  "iii", // 144 long sys_msync(unsigned long start, size_t len, int flags);
  "iii", // 145 ssize_t sys_readv(unsigned long fd, const struct iovec __user *vec, unsigned long vlen);
  "iii", // 146 ssize_t sys_writev(unsigned long fd, const struct iovec __user *vec, unsigned long vlen);
  "i", // 147 long sys_getsid(pid_t pid);
  "i", // 148 long sys_fdatasync(unsigned int fd);
  "", // 149 missing sys__sysctl
  "ii", // 150 long sys_mlock(unsigned long start, size_t len);
  "ii", // 151 long sys_munlock(unsigned long start, size_t len);
  "i", // 152 long sys_mlockall(int flags);
  "", // 153 long sys_munlockall(void);
  "ii", // 154 long sys_sched_setparam(pid_t pid, struct sched_param __user *param);
  "ii", // 155 long sys_sched_getparam(pid_t pid, struct sched_param __user *param);
  "iii", // 156 long sys_sched_setscheduler(pid_t pid, int policy, struct sched_param __user *param);
  "i", // 157 long sys_sched_getscheduler(pid_t pid);
  "", // 158 long sys_sched_yield(void);
  "i", // 159 long sys_sched_get_priority_max(int policy);
  "i", // 160 long sys_sched_get_priority_min(int policy);
  "ii", // 161 long sys_sched_rr_get_interval(pid_t pid, struct timespec __user *interval);
  "ii", // 162 long sys_nanosleep(struct timespec __user *rqtp, struct timespec __user *rmtp);
  "iiiii", // 163 unsigned long sys_mremap(unsigned long addr, unsigned long old_len, unsigned long new_len, unsigned long flags, unsigned long new_addr);
  "iii", // 164 long sys_setresuid(uid_t ruid, uid_t euid, uid_t suid);
  "iii", // 165 long sys_getresuid16(old_uid_t __user *ruid, old_uid_t __user *euid, old_uid_t __user *suid);
  "", // 166 missing sys_vm86 
  "", // 167 missing sys_query_module 
  "iii", // 168 long sys_poll(struct pollfd __user *ufds, unsigned int nfds, long timeout);
  "iii", // 169 long sys_nfsservctl(int cmd, struct nfsctl_arg __user *arg, void __user *res);
  "iii", // 170 int setresgid(gid_t rgid, gid_t egid, gid_t sgid);
  "iii", // 171 long sys_getresgid(gid_t __user *rgid, gid_t __user *egid, gid_t __user *sgid);
  "iiiii", // 172 long sys_prctl(int option, unsigned long arg2, unsigned long arg3, unsigned long arg4, unsigned long arg5);
  "i", // 173 int sigreturn(unsigned long __unused);
  "iii", // 174 int sigaction(int signum, const struct sigaction *act, struct sigaction *oldact);
  "iiii", // 175 int sys_rt_sigprocmask(int how, sigset_t __user *set, sigset_t __user *oset, size_t sigsetsize);
  "ii", // 176 long sys_rt_sigpending(sigset_t __user *set, size_t sigsetsize);
  "iiii", // 177 long sys_rt_sigtimedwait(const sigset_t __user *uthese, siginfo_t __user *uinfo, const struct timespec __user *uts, size_t sigsetsize);
  "iii", // 178 long sys_rt_sigqueueinfo(int pid, int sig, siginfo_t __user *uinfo);
  "i", // 179 int sigsuspend(const sigset_t *mask);
  "isii", // 180 ssize_t sys_pread64(unsigned int fd, char __user *buf, size_t count, loff_t pos);
  "isii", // 181 ssize_t sys_pwrite64(unsigned int fd, const char __user *buf, size_t count, loff_t pos);
  "sii", // 182 long sys_chown(const char __user *filename, uid_t user, gid_t group);
  "si", // 183 long sys_getcwd(char __user *buf, unsigned long size);
  "ii", // 184 long sys_capget(cap_user_header_t header, cap_user_data_t dataptr);
  "ii", // 185 long sys_capset(cap_user_header_t header, const cap_user_data_t data);
  "ii", // 186 int sigaltstack(const stack_t *ss, stack_t *oss);
  "iiii", // 187 ssize_t sys_sendfile(int out_fd, int in_fd, off_t __user *offset, size_t count);
  "", // 188 missing sys_getpmsg 
  "", // 189 missing sys_putpmsg 
  "", // 190 pid_t vfork(void);
  "ii", // 191 int getrlimit(int resource, struct rlimit *rlim);
  "iiiiii", // 192 void *mmap2(void *addr, size_t length, int prot, int flags, int fd, off_t pgoffset);
  "si", // 193 long sys_truncate64(const char __user *path, loff_t length);
  "ii", // 194 long sys_ftruncate64(unsigned int fd, loff_t length);
  "si", // 195 long sys_stat64(char __user *filename, struct stat64 __user *statbuf);
  "si", // 196 long sys_lstat64(char __user *filename, struct stat64 __user *statbuf);
  "ii", // 197 long sys_fstat64(unsigned long fd, struct stat64 __user *statbuf);
  "iii", // 198 int lchown(const char *path, uid_t owner, gid_t group);
  "", // 199 uid_t getuid(void);
  "", // 200 gid_t getgid(void);
  "", // 201 uid_t geteuid(void);
  "", // 202 gid_t getegid(void);
  "ii", // 203 int setreuid(uid_t ruid, uid_t euid);
  "ii", // 204 int setregid(gid_t rgid, gid_t egid);
  "ii", // 205 int getgroups(int size, gid_t list[]);
  "ii", // 206 int setgroups(size_t size, const gid_t *list);
  "iii", // 207 int fchown(int fd, uid_t owner, gid_t group);
  "iii", // 208 int setresuid(uid_t ruid, uid_t euid, uid_t suid);
  "iii", // 209 int getresuid(uid_t *ruid, uid_t *euid, uid_t *suid);
  "iii", // 210 int setresgid(gid_t rgid, gid_t egid, gid_t sgid);
  "iii", // 211 int getresgid(gid_t *rgid, gid_t *egid, gid_t *sgid);
  "iii", // 212 int chown(const char *path, uid_t owner, gid_t group);
  "i", // 213 int setuid(uid_t uid);
  "i", // 214 int setgid(gid_t gid);
  "i", // 215 int setfsuid(uid_t fsuid);
  "i", // 216 int setfsgid(uid_t fsgid);
  "ss", // 217 long sys_pivot_root(const char __user *new_root, const char __user *put_old);
  "iii", // 218 long sys_mincore(unsigned long start, size_t len, unsigned char __user * vec);
  "iii", // 219 long sys_madvise(unsigned long start, size_t len, int behavior);
  "iii", // 220 long sys_getdents64(4(unsigned int fd, struct linux_dirent64 __user *dirent, unsigned int count);
  "iii", // 221 long sys_fcntl64(unsigned int fd, unsigned int cmd, unsigned long arg);
  "", // 224 long sys_gettid(void);
  "iii", // 225 ssize_t sys_readahead(int fd, loff_t offset, size_t count);
  "ssiii", // 226 long sys_setxattr(const char __user *path, const char __user *name, const void __user *value, size_t size, int flags);
  "ssiii", // 227 long sys_lsetxattr(const char __user *path, const char __user *name, const void __user *value, size_t size, int flags);
  "isiii", // 228 long sys_fsetxattr(int fd, const char __user *name, const void __user *value, size_t size, int flags);
  "ssii", // 229 ssize_t sys_getxattr(const char __user *path, const char __user *name, void __user *value, size_t size);
  "ssii", // 230 ssize_t sys_lgetxattr(const char __user *path, const char __user *name, void __user *value, size_t size);
  "isii", // 231 ssize_t sys_fgetxattr(int fd, const char __user *name, void __user *value, size_t size);
  "ssi", // 232 ssize_t sys_listxattr(const char __user *path, char __user *list, size_t size);
  "ssi", // 233 ssize_t sys_llistxattr(const char __user *path, char __user *list, size_t size);
  "isi", // 234 ssize_t sys_flistxattr(int fd, char __user *list, size_t size);
  "ss", // 235 long sys_removexattr(const char __user *path, const char __user *name);
  "ss", // 236 long sys_lremovexattr(const char __user *path, const char __user *name);
  "is", // 237 long sys_fremovexattr(int fd, const char __user *name);
  "ii", // 238 long sys_tkill(int pid, int sig);
  "iiii", // 239 ssize_t sys_sendfile64(int out_fd, int in_fd, loff_t __user *offset, size_t count);
  "iiiiii", // 240 long sys_futex(u32 __user *uaddr, int op, u32 val, struct timespec __user *utime, u32 __user *uaddr2, u32 val3);
  "iii", // 241 long sys_sched_setaffinity(pid_t pid, unsigned int len, unsigned long __user *user_mask_ptr);
  "iii", // 242 long sys_sched_getaffinity(pid_t pid, unsigned int len, unsigned long __user *user_mask_ptr);
  "i", // 243 int set_thread_area(struct user_desc *u_info);
  "i", // 244 int get_thread_area(struct user_desc *u_info);
  "ii", // 245 int sys_io_setup(unsigned nr_reqs, aio_context_t __user *ctx);
  "i", // 246 long sys_io_destroy(aio_context_t ctx);
  "iiiii", // 247 long sys_io_getevents(aio_context_t ctx_id, long min_nr,long nr, struct io_event __user *events, struct timespec __user *timeout);
  "iii", // 248 long sys_io_submit(aio_context_t, long, struct iocb __user * __user *);
  "iii", // 249 long sys_io_cancel(aio_context_t ctx_id, struct iocb __user *iocb, struct io_event __user *result);
  "iiii", // 250 int sys_fadvise64(int fd, loff_t offset, size_t len, int advice); 
  "i", // 252 void sys_exit_group(int error_code);
  "isi", // 253 long sys_lookup_dcookie(u64 cookie64, char __user *buf, size_t len);
  "i", // 254 long sys_epoll_create(int size);
  "iiii", // 255 long sys_epoll_ctl(int epfd, int op, int fd, struct epoll_event __user *event);
  "iiii", // 256 long sys_epoll_wait(int epfd, struct epoll_event __user *events, int maxevents, int timeout);
  "iiiii", // 257 long sys_remap_file_pages(unsigned long start, unsigned long size, unsigned long prot, unsigned long pgoff, unsigned long flags);
  "i", // 258 long sys_set_tid_address(int __user *tidptr);
  "iii", // 259 long sys_timer_create(clockid_t which_clock, struct sigevent __user *timer_event_spec, timer_t __user * created_timer_id);
  "iiii", // 260 long sys_timer_settime(timer_t timer_id, int flags, const struct itimerspec __user *new_setting, struct itimerspec __user *old_setting);
  "ii", // 261 long sys_timer_gettime(timer_t timer_id, struct itimerspec __user *setting);
  "", // 262 missing sys_timer_getoverrun
  "i", // 263 long sys_timer_delete(timer_t timer_id);
  "ii", // 264 long sys_clock_settime(clockid_t which_clock, const struct timespec __user *tp);
  "ii", // 265 long sys_clock_gettime(clockid_t which_clock, struct timespec __user *tp);
  "ii", // 266 long sys_clock_getres(clockid_t which_clock, struct timespec __user *tp);
  "iiii", // 267 long sys_clock_nanosleep(clockid_t which_clock, int flags, const struct timespec __user *rqtp, struct timespec __user *rmtp);
  "sii", // 268 long sys_statfs64(const char __user *path, size_t sz, struct statfs64 __user *buf);
  "iii", // 269 long sys_fstatfs64(unsigned int fd, size_t sz, struct statfs64 __user *buf);
  "iii", // 270 long sys_tgkill(int tgid, int pid, int sig);
  "si", // 271 long sys_utimes(char __user *filename, struct timeval __user *utimes);
  "iiii", // 272 long sys_fadvise64_64(int fd, loff_t offset, loff_t len, int advice);
  "", // 273 missing sys_vserver 
  "iiiiii", // 274 long sys_mbind(unsigned long start, unsigned long len, unsigned long mode, unsigned long __user *nmask, unsigned long maxnode, unsigned flags);
  "iiiii", // 275 long sys_get_mempolicy(int __user *policy, unsigned long __user *nmask, unsigned long maxnode, unsigned long addr, unsigned long flags);
  "iii", // 276 long sys_set_mempolicy(int mode, unsigned long __user *nmask, unsigned long maxnode);
  "siii", // 277 long sys_mq_open(const char __user *name, int oflag, mode_t mode,  struct mq_attr __user *attr);
  "s", // 278 long sys_mq_unlink(const char __user *name);
  "isiii", // 279 long sys_mq_timedsend(mqd_t mqdes, const char __user *msg_ptr, size_t msg_len, unsigned int msg_prio, const struct timespec __user *abs_timeout);
  "isiii", // 280 ssize_t sys_mq_timedreceive(mqd_t mqdes, char __user *msg_ptr,  size_t msg_len, unsigned int __user *msg_prio, const struct timespec __user *abs_timeout);
  "ii", // 281 long sys_mq_notify(mqd_t mqdes, const struct sigevent __user *notification);
  "iii", // 282 long sys_mq_getsetattr(mqd_t mqdes, const struct mq_attr __user *mqstat, struct mq_attr __user *omqstat);
  "iiii", // 283 long sys_kexec_load(unsigned long entry, unsigned long nr_segments, struct kexec_segment __user *segments, unsigned long flags);
  "iiiii", // 284 long sys_waitid(int which, pid_t pid, struct siginfo __user *infop, int options, struct rusage __user *ru);
  "", // 285 missing sys_setaltroot 
  "ssiii", // 286 long sys_add_key(const char __user *_type, const char __user *_description, const void __user *_payload, size_t plen, key_serial_t destringid);
  "sssi", // 287 long sys_request_key(const char __user *_type, const char __user *_description, const char __user *_callout_info, key_serial_t destringid);
  "iiiii", // 288 long sys_keyctl(int cmd, unsigned long arg2, unsigned long arg3, unsigned long arg4, unsigned long arg5);
  "iii", // 289 long sys_ioprio_set(int which, int who, int ioprio);
  "ii", // 290 long sys_ioprio_get(int which, int who);
  "", // 291 long sys_inotify_init(void);
  "isi", // 292 long sys_inotify_add_watch(int fd, const char __user *path, u32 mask);
  "ii", // 293 long sys_inotify_rm_watch(int fd, u32 wd);
  "iiii", // 294 long sys_migrate_pages(pid_t pid, unsigned long maxnode, const unsigned long __user *from, const unsigned long __user *to); 
  "isii", // 295 long sys_openat(int dfd, const char __user *filename, int flags, int mode);
  "isi", // 296 long sys_mkdirat(int dfd, const char __user * pathname, int mode);
  "isii", // 297 long sys_mknodat(int dfd, const char __user * filename, int mode, unsigned dev);
  "isiii", // 298 long sys_fchownat(int dfd, const char __user *filename, uid_t user, gid_t group, int flag);
  "isi", // 299 long sys_futimesat(int dfd, char __user *filename, struct timeval __user *utimes);
  "isii", // 300 long sys_fstatat64(int dfd, char __user *filename, struct stat64 __user *statbuf, int flag);
  "isi", // 301 long sys_unlinkat(int dfd, const char __user * pathname, int flag);
  "isis", // 302 long sys_renameat(int olddfd, const char __user * oldname, int newdfd, const char __user * newname);
  "isisi", // 303 long sys_linkat(int olddfd, const char __user *oldname, int newdfd, const char __user *newname, int flags);
  "sis", // 304 long sys_symlinkat(const char __user * oldname, int newdfd, const char __user * newname)
  "issi", // 305 long sys_readlinkat(int dfd, const char __user *path, char __user *buf, int bufsiz);
  "isi", // 306 long sys_fchmodat(int dfd, const char __user * filename, mode_t mode);
  "isi", // 307 long sys_faccessat(int dfd, const char __user *filename, int mode);
  "iiiiii", // 308 int pselect(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, const struct timespec *timeout, const sigset_t *sigmask);
  "iiii", // 309 int ppoll(struct pollfd *fds, nfds_t nfds, const struct timespec *timeout, const sigset_t *sigmask);
  "i", // 310 long sys_unshare(unsigned long unshare_flags);
  "ii", // 311 long sys_set_robust_list(struct robust_list_head __user *head, size_t len);
  "iii", // 312 long sys_get_robust_list(int pid, struct robust_list_head __user * __user *head_ptr, size_t __user *len_ptr);
  "iiiiii", // 313 long sys_splice(int fd_in, loff_t __user *off_in, int fd_out, loff_t __user *off_out, size_t len, unsigned int flags);
  "iiii", // 314 long sys_sync_file_range(int fd, loff_t offset, loff_t nbytes, unsigned int flags);
  "iiii", // 315 long sys_tee(int fdin, int fdout, size_t len, unsigned int flags);
  "iiii", // 316 long sys_vmsplice(int fd, const struct iovec __user *iov, unsigned long nr_segs, unsigned int flags);
  "iiiiii", // 317 long sys_move_pages(pid_t pid, unsigned long nr_pages, const void __user * __user *pages, const int __user *nodes, int __user *status, int flags);
  "iii", // 318 long sys_getcpu(unsigned __user *cpu, unsigned __user *node,  struct getcpu_cache __user *cache);
  "iiii", // 319 long sys_epoll_wait(int epfd, struct epoll_event __user *events, int maxevents, int timeout);
  "isii", // 320 long sys_utimensat(int dfd, char __user *filename, struct timespec __user *utimes, int flags);
  "iii", // 321 long sys_signalfd(int ufd, sigset_t __user *user_mask, size_t sizemask);
  "ii", // 322 long sys_timerfd_create(int clockid, int flags);
  "i", // 323 long sys_eventfd(unsigned int count);
  "iiii", // 324 long sys_fallocate(int fd, int mode, loff_t offset, loff_t len);
  "iiii", // 325 long sys_timerfd_settime(int ufd, int flags, const struct itimerspec __user *utmr, struct itimerspec __user *otmr);
  "ii", // 326 long sys_timerfd_gettime(int ufd, struct itimerspec __user *otmr); 
  "iiii", // 327 long sys_signalfd4(int ufd, sigset_t __user *user_mask, size_t sizemask, int flags);
  "ii", // 328 long sys_eventfd2(unsigned int count, int flags);
  "i", // 329 long sys_epoll_create1(int flags);
  "iii", // 330 long sys_dup3(unsigned int oldfd, unsigned int newfd, int flags); 
  "", // 331 missing sys_pipe2 
  "i" // 332 long sys_inotify_init1(int flags);
}
