// NB: This code is auto-generated by make_iferret_code.pl. 
// It contains a large number of functions that take an info-flow
// op as input and return a pointer to a string representing it. 
#include <stdio.h>
#include "iferret_ops.h"

char *iferret_op_num_to_str(iferret_log_op_enum_t op_num) {
  char *rv=NULL;
  switch (op_num) { 
  case IFLO_AAA:
    rv = "IFLO_AAA";
    break;
  case IFLO_AAD:
    rv = "IFLO_AAD";
    break;
  case IFLO_AAM:
    rv = "IFLO_AAM";
    break;
  case IFLO_AAS:
    rv = "IFLO_AAS";
    break;
  case IFLO_ADC_T0_T1_CC:
    rv = "IFLO_ADC_T0_T1_CC";
    break;
  case IFLO_ADC_T0_T1_CC_MEMWRITE:
    rv = "IFLO_ADC_T0_T1_CC_MEMWRITE";
    break;
  case IFLO_ADDL_A0_AL:
    rv = "IFLO_ADDL_A0_AL";
    break;
  case IFLO_ADDL_A0_IM:
    rv = "IFLO_ADDL_A0_IM";
    break;
  case IFLO_ADDL_A0_SEG:
    rv = "IFLO_ADDL_A0_SEG";
    break;
  case IFLO_ADDL_A0_SS:
    rv = "IFLO_ADDL_A0_SS";
    break;
  case IFLO_ADDL_EDI_T0:
    rv = "IFLO_ADDL_EDI_T0";
    break;
  case IFLO_ADDL_ESI_T0:
    rv = "IFLO_ADDL_ESI_T0";
    break;
  case IFLO_ADDL_ESP_2:
    rv = "IFLO_ADDL_ESP_2";
    break;
  case IFLO_ADDL_ESP_4:
    rv = "IFLO_ADDL_ESP_4";
    break;
  case IFLO_ADDL_ESP_IM:
    rv = "IFLO_ADDL_ESP_IM";
    break;
  case IFLO_ADDL_T0_IM:
    rv = "IFLO_ADDL_T0_IM";
    break;
  case IFLO_ADDL_T0_T1:
    rv = "IFLO_ADDL_T0_T1";
    break;
  case IFLO_ADDL_T1_IM:
    rv = "IFLO_ADDL_T1_IM";
    break;
  case IFLO_ADDW_EDI_T0:
    rv = "IFLO_ADDW_EDI_T0";
    break;
  case IFLO_ADDW_ESI_T0:
    rv = "IFLO_ADDW_ESI_T0";
    break;
  case IFLO_ADDW_ESP_2:
    rv = "IFLO_ADDW_ESP_2";
    break;
  case IFLO_ADDW_ESP_4:
    rv = "IFLO_ADDW_ESP_4";
    break;
  case IFLO_ADDW_ESP_IM:
    rv = "IFLO_ADDW_ESP_IM";
    break;
  case IFLO_ADD_BIT_A0_T1:
    rv = "IFLO_ADD_BIT_A0_T1";
    break;
  case IFLO_ANDL_A0_FFFF:
    rv = "IFLO_ANDL_A0_FFFF";
    break;
  case IFLO_ANDL_T0_FFFF:
    rv = "IFLO_ANDL_T0_FFFF";
    break;
  case IFLO_ANDL_T0_IM:
    rv = "IFLO_ANDL_T0_IM";
    break;
  case IFLO_ANDL_T0_T1:
    rv = "IFLO_ANDL_T0_T1";
    break;
  case IFLO_ARPL:
    rv = "IFLO_ARPL";
    break;
  case IFLO_BSF_T0_CC:
    rv = "IFLO_BSF_T0_CC";
    break;
  case IFLO_BSR_T0_CC:
    rv = "IFLO_BSR_T0_CC";
    break;
  case IFLO_BSWAPL_T0:
    rv = "IFLO_BSWAPL_T0";
    break;
  case IFLO_BTC_T0_T1_CC:
    rv = "IFLO_BTC_T0_T1_CC";
    break;
  case IFLO_BTR_T0_T1_CC:
    rv = "IFLO_BTR_T0_T1_CC";
    break;
  case IFLO_BTS_T0_T1_CC:
    rv = "IFLO_BTS_T0_T1_CC";
    break;
  case IFLO_CLTS:
    rv = "IFLO_CLTS";
    break;
  case IFLO_CMPXCHG8B_PART1:
    rv = "IFLO_CMPXCHG8B_PART1";
    break;
  case IFLO_CMPXCHG8B_PART2:
    rv = "IFLO_CMPXCHG8B_PART2";
    break;
  case IFLO_CMPXCHG_T0_T1_EAX_CC:
    rv = "IFLO_CMPXCHG_T0_T1_EAX_CC";
    break;
  case IFLO_CMPXCHG_T0_T1_EAX_CC_CASE2:
    rv = "IFLO_CMPXCHG_T0_T1_EAX_CC_CASE2";
    break;
  case IFLO_CMPXCHG_T0_T1_EAX_CC_MEMWRITE:
    rv = "IFLO_CMPXCHG_T0_T1_EAX_CC_MEMWRITE";
    break;
  case IFLO_CPUID:
    rv = "IFLO_CPUID";
    break;
  case IFLO_CPU_READ_ADDR:
    rv = "IFLO_CPU_READ_ADDR";
    break;
  case IFLO_CPU_WRITE_ADDR:
    rv = "IFLO_CPU_WRITE_ADDR";
    break;
  case IFLO_DAA:
    rv = "IFLO_DAA";
    break;
  case IFLO_DAS:
    rv = "IFLO_DAS";
    break;
  case IFLO_DECL_ECX:
    rv = "IFLO_DECL_ECX";
    break;
  case IFLO_DECL_T0:
    rv = "IFLO_DECL_T0";
    break;
  case IFLO_DECW_ECX:
    rv = "IFLO_DECW_ECX";
    break;
  case IFLO_DIVB_AL_T0:
    rv = "IFLO_DIVB_AL_T0";
    break;
  case IFLO_DIVL_EAX_T0:
    rv = "IFLO_DIVL_EAX_T0";
    break;
  case IFLO_ENTER_LEVEL:
    rv = "IFLO_ENTER_LEVEL";
    break;
  case IFLO_FNSTSW_EAX:
    rv = "IFLO_FNSTSW_EAX";
    break;
  case IFLO_HD_TRANSFER:
    rv = "IFLO_HD_TRANSFER";
    break;
  case IFLO_HD_TRANSFER_PART1:
    rv = "IFLO_HD_TRANSFER_PART1";
    break;
  case IFLO_HD_TRANSFER_PART2:
    rv = "IFLO_HD_TRANSFER_PART2";
    break;
  case IFLO_IDIVB_AL_T0:
    rv = "IFLO_IDIVB_AL_T0";
    break;
  case IFLO_IDIVL_EAX_T0:
    rv = "IFLO_IDIVL_EAX_T0";
    break;
  case IFLO_IDIVW_AX_T0:
    rv = "IFLO_IDIVW_AX_T0";
    break;
  case IFLO_IMULB_A0_T0:
    rv = "IFLO_IMULB_A0_T0";
    break;
  case IFLO_IMULL_EAX_T0:
    rv = "IFLO_IMULL_EAX_T0";
    break;
  case IFLO_IMULL_T0_T1:
    rv = "IFLO_IMULL_T0_T1";
    break;
  case IFLO_IMULW_AX_T0:
    rv = "IFLO_IMULW_AX_T0";
    break;
  case IFLO_IMULW_T0_T1:
    rv = "IFLO_IMULW_T0_T1";
    break;
  case IFLO_INCL_T0:
    rv = "IFLO_INCL_T0";
    break;
  case IFLO_INVLPG_A0:
    rv = "IFLO_INVLPG_A0";
    break;
  case IFLO_IN_DX_T0:
    rv = "IFLO_IN_DX_T0";
    break;
  case IFLO_IN_T0_T1:
    rv = "IFLO_IN_T0_T1";
    break;
  case IFLO_IRET:
    rv = "IFLO_IRET";
    break;
  case IFLO_IRET_PROTECTED:
    rv = "IFLO_IRET_PROTECTED";
    break;
  case IFLO_IRET_REAL:
    rv = "IFLO_IRET_REAL";
    break;
  case IFLO_JMP_T0:
    rv = "IFLO_JMP_T0";
    break;
  case IFLO_KEYBOARD_INPUT:
    rv = "IFLO_KEYBOARD_INPUT";
    break;
  case IFLO_LAR:
    rv = "IFLO_LAR";
    break;
  case IFLO_LCALL_PROTECTED_T0_T1:
    rv = "IFLO_LCALL_PROTECTED_T0_T1";
    break;
  case IFLO_LCALL_REAL_T0_T1:
    rv = "IFLO_LCALL_REAL_T0_T1";
    break;
  case IFLO_LLDT_T0:
    rv = "IFLO_LLDT_T0";
    break;
  case IFLO_LMSW_T0:
    rv = "IFLO_LMSW_T0";
    break;
  case IFLO_LRET_PROTECTED:
    rv = "IFLO_LRET_PROTECTED";
    break;
  case IFLO_LSL:
    rv = "IFLO_LSL";
    break;
  case IFLO_LTR_T0:
    rv = "IFLO_LTR_T0";
    break;
  case IFLO_MMU_LD_DIRECT_B:
    rv = "IFLO_MMU_LD_DIRECT_B";
    break;
  case IFLO_MMU_LD_DIRECT_L:
    rv = "IFLO_MMU_LD_DIRECT_L";
    break;
  case IFLO_MMU_LD_DIRECT_Q:
    rv = "IFLO_MMU_LD_DIRECT_Q";
    break;
  case IFLO_MMU_LD_DIRECT_W:
    rv = "IFLO_MMU_LD_DIRECT_W";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_IO_ALIGNED_B:
    rv = "IFLO_MMU_PHYS_ADDR_LD_IO_ALIGNED_B";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_IO_ALIGNED_L:
    rv = "IFLO_MMU_PHYS_ADDR_LD_IO_ALIGNED_L";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_IO_ALIGNED_Q:
    rv = "IFLO_MMU_PHYS_ADDR_LD_IO_ALIGNED_Q";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_IO_ALIGNED_W:
    rv = "IFLO_MMU_PHYS_ADDR_LD_IO_ALIGNED_W";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_IO_PART2_B:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_IO_PART2_B";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_IO_PART2_L:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_IO_PART2_L";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_IO_PART2_Q:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_IO_PART2_Q";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_IO_PART2_W:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_IO_PART2_W";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART1_B:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART1_B";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART1_L:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART1_L";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART1_Q:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART1_Q";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART1_W:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART1_W";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART2_B:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART2_B";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART2_L:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART2_L";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART2_Q:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART2_Q";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART2_W:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_DIFFERENT_PAGE_PART2_W";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_SAME_PAGE_B:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_SAME_PAGE_B";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_SAME_PAGE_L:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_SAME_PAGE_L";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_SAME_PAGE_Q:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_SAME_PAGE_Q";
    break;
  case IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_SAME_PAGE_W:
    rv = "IFLO_MMU_PHYS_ADDR_LD_UNALIGNED_SAME_PAGE_W";
    break;
  case IFLO_MMU_ST_DIRECT_B:
    rv = "IFLO_MMU_ST_DIRECT_B";
    break;
  case IFLO_MMU_ST_DIRECT_L:
    rv = "IFLO_MMU_ST_DIRECT_L";
    break;
  case IFLO_MMU_ST_DIRECT_Q:
    rv = "IFLO_MMU_ST_DIRECT_Q";
    break;
  case IFLO_MMU_ST_DIRECT_W:
    rv = "IFLO_MMU_ST_DIRECT_W";
    break;
  case IFLO_MMU_ST_IO_ALIGNED_B:
    rv = "IFLO_MMU_ST_IO_ALIGNED_B";
    break;
  case IFLO_MMU_ST_IO_ALIGNED_L:
    rv = "IFLO_MMU_ST_IO_ALIGNED_L";
    break;
  case IFLO_MMU_ST_IO_ALIGNED_Q:
    rv = "IFLO_MMU_ST_IO_ALIGNED_Q";
    break;
  case IFLO_MMU_ST_IO_ALIGNED_W:
    rv = "IFLO_MMU_ST_IO_ALIGNED_W";
    break;
  case IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_IO_PART2_B:
    rv = "IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_IO_PART2_B";
    break;
  case IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_IO_PART2_L:
    rv = "IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_IO_PART2_L";
    break;
  case IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_IO_PART2_Q:
    rv = "IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_IO_PART2_Q";
    break;
  case IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_IO_PART2_W:
    rv = "IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_IO_PART2_W";
    break;
  case IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART1_B:
    rv = "IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART1_B";
    break;
  case IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART1_L:
    rv = "IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART1_L";
    break;
  case IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART1_Q:
    rv = "IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART1_Q";
    break;
  case IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART1_W:
    rv = "IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART1_W";
    break;
  case IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART2_B:
    rv = "IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART2_B";
    break;
  case IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART2_L:
    rv = "IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART2_L";
    break;
  case IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART2_Q:
    rv = "IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART2_Q";
    break;
  case IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART2_W:
    rv = "IFLO_MMU_ST_UNALIGNED_DIFFERENT_PAGE_PART2_W";
    break;
  case IFLO_MMU_ST_UNALIGNED_SAME_PAGE_B:
    rv = "IFLO_MMU_ST_UNALIGNED_SAME_PAGE_B";
    break;
  case IFLO_MMU_ST_UNALIGNED_SAME_PAGE_L:
    rv = "IFLO_MMU_ST_UNALIGNED_SAME_PAGE_L";
    break;
  case IFLO_MMU_ST_UNALIGNED_SAME_PAGE_Q:
    rv = "IFLO_MMU_ST_UNALIGNED_SAME_PAGE_Q";
    break;
  case IFLO_MMU_ST_UNALIGNED_SAME_PAGE_W:
    rv = "IFLO_MMU_ST_UNALIGNED_SAME_PAGE_W";
    break;
  case IFLO_MMU_TLB_FILL:
    rv = "IFLO_MMU_TLB_FILL";
    break;
  case IFLO_MOVB_EFLAGS_T0:
    rv = "IFLO_MOVB_EFLAGS_T0";
    break;
  case IFLO_MOVL_A0_IM:
    rv = "IFLO_MOVL_A0_IM";
    break;
  case IFLO_MOVL_A0_SEG:
    rv = "IFLO_MOVL_A0_SEG";
    break;
  case IFLO_MOVL_CRN_T0:
    rv = "IFLO_MOVL_CRN_T0";
    break;
  case IFLO_MOVL_DRN_T0:
    rv = "IFLO_MOVL_DRN_T0";
    break;
  case IFLO_MOVL_EFLAGS_T0:
    rv = "IFLO_MOVL_EFLAGS_T0";
    break;
  case IFLO_MOVL_EFLAGS_T0_CPL0:
    rv = "IFLO_MOVL_EFLAGS_T0_CPL0";
    break;
  case IFLO_MOVL_EFLAGS_T0_IO:
    rv = "IFLO_MOVL_EFLAGS_T0_IO";
    break;
  case IFLO_MOVL_EIP_IM:
    rv = "IFLO_MOVL_EIP_IM";
    break;
  case IFLO_MOVL_ENV_T0:
    rv = "IFLO_MOVL_ENV_T0";
    break;
  case IFLO_MOVL_ENV_T1:
    rv = "IFLO_MOVL_ENV_T1";
    break;
  case IFLO_MOVL_T0_0:
    rv = "IFLO_MOVL_T0_0";
    break;
  case IFLO_MOVL_T0_DSHIFT:
    rv = "IFLO_MOVL_T0_DSHIFT";
    break;
  case IFLO_MOVL_T0_EFLAGS:
    rv = "IFLO_MOVL_T0_EFLAGS";
    break;
  case IFLO_MOVL_T0_ENV:
    rv = "IFLO_MOVL_T0_ENV";
    break;
  case IFLO_MOVL_T0_IM:
    rv = "IFLO_MOVL_T0_IM";
    break;
  case IFLO_MOVL_T0_IMU:
    rv = "IFLO_MOVL_T0_IMU";
    break;
  case IFLO_MOVL_T0_SEG:
    rv = "IFLO_MOVL_T0_SEG";
    break;
  case IFLO_MOVL_T0_T1:
    rv = "IFLO_MOVL_T0_T1";
    break;
  case IFLO_MOVL_T1_A0:
    rv = "IFLO_MOVL_T1_A0";
    break;
  case IFLO_MOVL_T1_IM:
    rv = "IFLO_MOVL_T1_IM";
    break;
  case IFLO_MOVL_T1_IMU:
    rv = "IFLO_MOVL_T1_IMU";
    break;
  case IFLO_MOVSBL_T0_T0:
    rv = "IFLO_MOVSBL_T0_T0";
    break;
  case IFLO_MOVSBW_AX_AL:
    rv = "IFLO_MOVSBW_AX_AL";
    break;
  case IFLO_MOVSLQ_EDX_EAX:
    rv = "IFLO_MOVSLQ_EDX_EAX";
    break;
  case IFLO_MOVSWL_DX_AX:
    rv = "IFLO_MOVSWL_DX_AX";
    break;
  case IFLO_MOVSWL_EAX_AX:
    rv = "IFLO_MOVSWL_EAX_AX";
    break;
  case IFLO_MOVSWL_T0_T0:
    rv = "IFLO_MOVSWL_T0_T0";
    break;
  case IFLO_MOVTL_ENV_T0:
    rv = "IFLO_MOVTL_ENV_T0";
    break;
  case IFLO_MOVTL_ENV_T1:
    rv = "IFLO_MOVTL_ENV_T1";
    break;
  case IFLO_MOVTL_T0_CR8:
    rv = "IFLO_MOVTL_T0_CR8";
    break;
  case IFLO_MOVTL_T0_ENV:
    rv = "IFLO_MOVTL_T0_ENV";
    break;
  case IFLO_MOVTL_T1_ENV:
    rv = "IFLO_MOVTL_T1_ENV";
    break;
  case IFLO_MOVW_EFLAGS_T0:
    rv = "IFLO_MOVW_EFLAGS_T0";
    break;
  case IFLO_MOVW_EFLAGS_T0_CPL0:
    rv = "IFLO_MOVW_EFLAGS_T0_CPL0";
    break;
  case IFLO_MOVW_EFLAGS_T0_IO:
    rv = "IFLO_MOVW_EFLAGS_T0_IO";
    break;
  case IFLO_MOVZBL_T0_T0:
    rv = "IFLO_MOVZBL_T0_T0";
    break;
  case IFLO_MOVZWL_T0_T0:
    rv = "IFLO_MOVZWL_T0_T0";
    break;
  case IFLO_MOV_T0_CC:
    rv = "IFLO_MOV_T0_CC";
    break;
  case IFLO_MULB_A0_T0:
    rv = "IFLO_MULB_A0_T0";
    break;
  case IFLO_MULL_EAX_T0:
    rv = "IFLO_MULL_EAX_T0";
    break;
  case IFLO_MULW_AX_T0:
    rv = "IFLO_MULW_AX_T0";
    break;
  case IFLO_NEGL_T0:
    rv = "IFLO_NEGL_T0";
    break;
  case IFLO_NETWORK_INPUT_BYTE_T0:
    rv = "IFLO_NETWORK_INPUT_BYTE_T0";
    break;
  case IFLO_NETWORK_INPUT_BYTE_T1:
    rv = "IFLO_NETWORK_INPUT_BYTE_T1";
    break;
  case IFLO_NETWORK_INPUT_LONG_T0:
    rv = "IFLO_NETWORK_INPUT_LONG_T0";
    break;
  case IFLO_NETWORK_INPUT_LONG_T1:
    rv = "IFLO_NETWORK_INPUT_LONG_T1";
    break;
  case IFLO_NETWORK_INPUT_WORD_T0:
    rv = "IFLO_NETWORK_INPUT_WORD_T0";
    break;
  case IFLO_NETWORK_INPUT_WORD_T1:
    rv = "IFLO_NETWORK_INPUT_WORD_T1";
    break;
  case IFLO_NETWORK_OUTPUT_BYTE_T0:
    rv = "IFLO_NETWORK_OUTPUT_BYTE_T0";
    break;
  case IFLO_NETWORK_OUTPUT_BYTE_T1:
    rv = "IFLO_NETWORK_OUTPUT_BYTE_T1";
    break;
  case IFLO_NETWORK_OUTPUT_LONG_T0:
    rv = "IFLO_NETWORK_OUTPUT_LONG_T0";
    break;
  case IFLO_NETWORK_OUTPUT_LONG_T1:
    rv = "IFLO_NETWORK_OUTPUT_LONG_T1";
    break;
  case IFLO_NETWORK_OUTPUT_WORD_T0:
    rv = "IFLO_NETWORK_OUTPUT_WORD_T0";
    break;
  case IFLO_NETWORK_OUTPUT_WORD_T1:
    rv = "IFLO_NETWORK_OUTPUT_WORD_T1";
    break;
  case IFLO_NEW_KEYBOARD_LABEL:
    rv = "IFLO_NEW_KEYBOARD_LABEL";
    break;
  case IFLO_NOTL_T0:
    rv = "IFLO_NOTL_T0";
    break;
  case IFLO_OPREG_TEMPL_ADDL_A0_R:
    rv = "IFLO_OPREG_TEMPL_ADDL_A0_R";
    break;
  case IFLO_OPREG_TEMPL_ADDL_A0_R_S1:
    rv = "IFLO_OPREG_TEMPL_ADDL_A0_R_S1";
    break;
  case IFLO_OPREG_TEMPL_ADDL_A0_R_S2:
    rv = "IFLO_OPREG_TEMPL_ADDL_A0_R_S2";
    break;
  case IFLO_OPREG_TEMPL_ADDL_A0_R_S3:
    rv = "IFLO_OPREG_TEMPL_ADDL_A0_R_S3";
    break;
  case IFLO_OPREG_TEMPL_CMOVL_R_T1_T0:
    rv = "IFLO_OPREG_TEMPL_CMOVL_R_T1_T0";
    break;
  case IFLO_OPREG_TEMPL_CMOVW_R_T1_T0:
    rv = "IFLO_OPREG_TEMPL_CMOVW_R_T1_T0";
    break;
  case IFLO_OPREG_TEMPL_MOVB_R_T0:
    rv = "IFLO_OPREG_TEMPL_MOVB_R_T0";
    break;
  case IFLO_OPREG_TEMPL_MOVB_R_T1:
    rv = "IFLO_OPREG_TEMPL_MOVB_R_T1";
    break;
  case IFLO_OPREG_TEMPL_MOVH_R_T0:
    rv = "IFLO_OPREG_TEMPL_MOVH_R_T0";
    break;
  case IFLO_OPREG_TEMPL_MOVH_R_T1:
    rv = "IFLO_OPREG_TEMPL_MOVH_R_T1";
    break;
  case IFLO_OPREG_TEMPL_MOVH_T0_R:
    rv = "IFLO_OPREG_TEMPL_MOVH_T0_R";
    break;
  case IFLO_OPREG_TEMPL_MOVH_T1_R:
    rv = "IFLO_OPREG_TEMPL_MOVH_T1_R";
    break;
  case IFLO_OPREG_TEMPL_MOVL_A0_R:
    rv = "IFLO_OPREG_TEMPL_MOVL_A0_R";
    break;
  case IFLO_OPREG_TEMPL_MOVL_R_A0:
    rv = "IFLO_OPREG_TEMPL_MOVL_R_A0";
    break;
  case IFLO_OPREG_TEMPL_MOVL_R_T0:
    rv = "IFLO_OPREG_TEMPL_MOVL_R_T0";
    break;
  case IFLO_OPREG_TEMPL_MOVL_R_T1:
    rv = "IFLO_OPREG_TEMPL_MOVL_R_T1";
    break;
  case IFLO_OPREG_TEMPL_MOVL_T0_R:
    rv = "IFLO_OPREG_TEMPL_MOVL_T0_R";
    break;
  case IFLO_OPREG_TEMPL_MOVL_T1_R:
    rv = "IFLO_OPREG_TEMPL_MOVL_T1_R";
    break;
  case IFLO_OPREG_TEMPL_MOVW_R_A0:
    rv = "IFLO_OPREG_TEMPL_MOVW_R_A0";
    break;
  case IFLO_OPREG_TEMPL_MOVW_R_T0:
    rv = "IFLO_OPREG_TEMPL_MOVW_R_T0";
    break;
  case IFLO_OPREG_TEMPL_MOVW_R_T1:
    rv = "IFLO_OPREG_TEMPL_MOVW_R_T1";
    break;
  case IFLO_ORL_T0_T1:
    rv = "IFLO_ORL_T0_T1";
    break;
  case IFLO_PID_CHANGE:
    rv = "IFLO_PID_CHANGE";
    break;
  case IFLO_PROTECTED_T0_T1:
    rv = "IFLO_PROTECTED_T0_T1";
    break;
  case IFLO_RCL_T0_T1_CC:
    rv = "IFLO_RCL_T0_T1_CC";
    break;
  case IFLO_RCL_T0_T1_CC_MEMWRITE:
    rv = "IFLO_RCL_T0_T1_CC_MEMWRITE";
    break;
  case IFLO_RCR_T0_T1_CC:
    rv = "IFLO_RCR_T0_T1_CC";
    break;
  case IFLO_RCR_T0_T1_CC_MEMWRITE:
    rv = "IFLO_RCR_T0_T1_CC_MEMWRITE";
    break;
  case IFLO_RDMSR:
    rv = "IFLO_RDMSR";
    break;
  case IFLO_RDTSC:
    rv = "IFLO_RDTSC";
    break;
  case IFLO_RESTORE_ENV:
    rv = "IFLO_RESTORE_ENV";
    break;
  case IFLO_ROL_T0_T1:
    rv = "IFLO_ROL_T0_T1";
    break;
  case IFLO_ROL_T0_T1_CC:
    rv = "IFLO_ROL_T0_T1_CC";
    break;
  case IFLO_ROL_T0_T1_CC_MEMWRITE:
    rv = "IFLO_ROL_T0_T1_CC_MEMWRITE";
    break;
  case IFLO_ROL_T0_T1_MEMRITE:
    rv = "IFLO_ROL_T0_T1_MEMRITE";
    break;
  case IFLO_ROR_T0_T1:
    rv = "IFLO_ROR_T0_T1";
    break;
  case IFLO_ROR_T0_T1_CC:
    rv = "IFLO_ROR_T0_T1_CC";
    break;
  case IFLO_ROR_T0_T1_CC_MEMRITE:
    rv = "IFLO_ROR_T0_T1_CC_MEMRITE";
    break;
  case IFLO_ROR_T0_T1_MEMWRITE:
    rv = "IFLO_ROR_T0_T1_MEMWRITE";
    break;
  case IFLO_SALC:
    rv = "IFLO_SALC";
    break;
  case IFLO_SAR_T0_T1:
    rv = "IFLO_SAR_T0_T1";
    break;
  case IFLO_SAR_T0_T1_CC:
    rv = "IFLO_SAR_T0_T1_CC";
    break;
  case IFLO_SAR_T0_T1_CC_MEMWRITE:
    rv = "IFLO_SAR_T0_T1_CC_MEMWRITE";
    break;
  case IFLO_SAVE_REG:
    rv = "IFLO_SAVE_REG";
    break;
  case IFLO_SBB_T0_T1_CC:
    rv = "IFLO_SBB_T0_T1_CC";
    break;
  case IFLO_SBB_T0_T1_CC_MEMWRITE:
    rv = "IFLO_SBB_T0_T1_CC_MEMWRITE";
    break;
  case IFLO_SEG_T0:
    rv = "IFLO_SEG_T0";
    break;
  case IFLO_SEG_T0_VM:
    rv = "IFLO_SEG_T0_VM";
    break;
  case IFLO_SETBE_T0_CC:
    rv = "IFLO_SETBE_T0_CC";
    break;
  case IFLO_SETBE_T0_SUB:
    rv = "IFLO_SETBE_T0_SUB";
    break;
  case IFLO_SETB_T0_CC:
    rv = "IFLO_SETB_T0_CC";
    break;
  case IFLO_SETB_T0_SUB:
    rv = "IFLO_SETB_T0_SUB";
    break;
  case IFLO_SETLE_T0_CC:
    rv = "IFLO_SETLE_T0_CC";
    break;
  case IFLO_SETLE_T0_SUB:
    rv = "IFLO_SETLE_T0_SUB";
    break;
  case IFLO_SETL_T0_CC:
    rv = "IFLO_SETL_T0_CC";
    break;
  case IFLO_SETL_T0_SUB:
    rv = "IFLO_SETL_T0_SUB";
    break;
  case IFLO_SETO_T0_CC:
    rv = "IFLO_SETO_T0_CC";
    break;
  case IFLO_SETP_T0_CC:
    rv = "IFLO_SETP_T0_CC";
    break;
  case IFLO_SETS_T0_CC:
    rv = "IFLO_SETS_T0_CC";
    break;
  case IFLO_SETS_T0_SUB:
    rv = "IFLO_SETS_T0_SUB";
    break;
  case IFLO_SETZ_T0_CC:
    rv = "IFLO_SETZ_T0_CC";
    break;
  case IFLO_SETZ_T0_SUB:
    rv = "IFLO_SETZ_T0_SUB";
    break;
  case IFLO_SET_CPL:
    rv = "IFLO_SET_CPL";
    break;
  case IFLO_SHLD_T0_T1_ECX_CC:
    rv = "IFLO_SHLD_T0_T1_ECX_CC";
    break;
  case IFLO_SHLD_T0_T1_ECX_CC_MEMWRITE:
    rv = "IFLO_SHLD_T0_T1_ECX_CC_MEMWRITE";
    break;
  case IFLO_SHLD_T0_T1_IM_CC:
    rv = "IFLO_SHLD_T0_T1_IM_CC";
    break;
  case IFLO_SHLD_T0_T1_IM_CC_MEMWRITE:
    rv = "IFLO_SHLD_T0_T1_IM_CC_MEMWRITE";
    break;
  case IFLO_SHL_T0_T1:
    rv = "IFLO_SHL_T0_T1";
    break;
  case IFLO_SHL_T0_T1_CC:
    rv = "IFLO_SHL_T0_T1_CC";
    break;
  case IFLO_SHL_T0_T1_CC_MEMWRITE:
    rv = "IFLO_SHL_T0_T1_CC_MEMWRITE";
    break;
  case IFLO_SHRD_T0_T1_ECX_CC:
    rv = "IFLO_SHRD_T0_T1_ECX_CC";
    break;
  case IFLO_SHRD_T0_T1_ECX_CC_MEMWRITE:
    rv = "IFLO_SHRD_T0_T1_ECX_CC_MEMWRITE";
    break;
  case IFLO_SHRD_T0_T1_IM_CC:
    rv = "IFLO_SHRD_T0_T1_IM_CC";
    break;
  case IFLO_SHRD_T0_T1_IM_CC_MEMWRITE:
    rv = "IFLO_SHRD_T0_T1_IM_CC_MEMWRITE";
    break;
  case IFLO_SHR_T0_T1:
    rv = "IFLO_SHR_T0_T1";
    break;
  case IFLO_SHR_T0_T1_CC:
    rv = "IFLO_SHR_T0_T1_CC";
    break;
  case IFLO_SHR_T0_T1_CC_MEMWRITE:
    rv = "IFLO_SHR_T0_T1_CC_MEMWRITE";
    break;
  case IFLO_SPAWN_NEW_PID:
    rv = "IFLO_SPAWN_NEW_PID";
    break;
  case IFLO_SUBL_A0_2:
    rv = "IFLO_SUBL_A0_2";
    break;
  case IFLO_SUBL_A0_4:
    rv = "IFLO_SUBL_A0_4";
    break;
  case IFLO_SUBL_T0_T1:
    rv = "IFLO_SUBL_T0_T1";
    break;
  case IFLO_SYSENTER:
    rv = "IFLO_SYSENTER";
    break;
  case IFLO_SYSEXIT:
    rv = "IFLO_SYSEXIT";
    break;
  case IFLO_SYSEXIT_RET:
    rv = "IFLO_SYSEXIT_RET";
    break;
  case IFLO_TB_HEAD_EIP:
    rv = "IFLO_TB_HEAD_EIP";
    break;
  case IFLO_UID_CHANGE:
    rv = "IFLO_UID_CHANGE";
    break;
  case IFLO_WRMSR:
    rv = "IFLO_WRMSR";
    break;
  case IFLO_XORL_T0_T1:
    rv = "IFLO_XORL_T0_T1";
    break;
  case IFLO_XOR_T0_1:
    rv = "IFLO_XOR_T0_1";
    break;
  case ILFO_OPS_MEM_LDL_T0_A0:
    rv = "ILFO_OPS_MEM_LDL_T0_A0";
    break;
  case ILFO_OPS_MEM_LDL_T1_A0:
    rv = "ILFO_OPS_MEM_LDL_T1_A0";
    break;
  case ILFO_OPS_MEM_LDSB_T0_A0:
    rv = "ILFO_OPS_MEM_LDSB_T0_A0";
    break;
  case ILFO_OPS_MEM_LDSB_T1_A0:
    rv = "ILFO_OPS_MEM_LDSB_T1_A0";
    break;
  case ILFO_OPS_MEM_LDSW_T0_A0:
    rv = "ILFO_OPS_MEM_LDSW_T0_A0";
    break;
  case ILFO_OPS_MEM_LDSW_T1_A0:
    rv = "ILFO_OPS_MEM_LDSW_T1_A0";
    break;
  case ILFO_OPS_MEM_LDUB_T0_A0:
    rv = "ILFO_OPS_MEM_LDUB_T0_A0";
    break;
  case ILFO_OPS_MEM_LDUB_T1_A0:
    rv = "ILFO_OPS_MEM_LDUB_T1_A0";
    break;
  case ILFO_OPS_MEM_LDUW_T0_A0:
    rv = "ILFO_OPS_MEM_LDUW_T0_A0";
    break;
  case ILFO_OPS_MEM_LDUW_T1_A0:
    rv = "ILFO_OPS_MEM_LDUW_T1_A0";
    break;
  case ILFO_OPS_MEM_STB_T0_A0:
    rv = "ILFO_OPS_MEM_STB_T0_A0";
    break;
  case ILFO_OPS_MEM_STL_T0_A0:
    rv = "ILFO_OPS_MEM_STL_T0_A0";
    break;
  case ILFO_OPS_MEM_STL_T1_A0:
    rv = "ILFO_OPS_MEM_STL_T1_A0";
    break;
  case ILFO_OPS_MEM_STW_T0_A0:
    rv = "ILFO_OPS_MEM_STW_T0_A0";
    break;
  case ILFO_OPS_MEM_STW_T1_A0:
    rv = "ILFO_OPS_MEM_STW_T1_A0";
    break;
  case IFLO_SYS_CALLS_START:
    rv = "IFLO_SYS_CALLS_START";
    break;
  case IFLO_SYS_SYS_RESTART_SYSCALL:
    rv = "IFLO_SYS_SYS_RESTART_SYSCALL";
    break;
  case IFLO_SYS_SYS_EXIT:
    rv = "IFLO_SYS_SYS_EXIT";
    break;
  case IFLO_SYS_FORK:
    rv = "IFLO_SYS_FORK";
    break;
  case IFLO_SYS_SYS_READ:
    rv = "IFLO_SYS_SYS_READ";
    break;
  case IFLO_SYS_SYS_WRITE:
    rv = "IFLO_SYS_SYS_WRITE";
    break;
  case IFLO_SYS_SYS_OPEN:
    rv = "IFLO_SYS_SYS_OPEN";
    break;
  case IFLO_SYS_SYS_CLOSE:
    rv = "IFLO_SYS_SYS_CLOSE";
    break;
  case IFLO_SYS_SYS_WAITPID:
    rv = "IFLO_SYS_SYS_WAITPID";
    break;
  case IFLO_SYS_SYS_CREAT:
    rv = "IFLO_SYS_SYS_CREAT";
    break;
  case IFLO_SYS_SYS_LINK:
    rv = "IFLO_SYS_SYS_LINK";
    break;
  case IFLO_SYS_SYS_UNLINK:
    rv = "IFLO_SYS_SYS_UNLINK";
    break;
  case IFLO_SYS_EXECVE:
    rv = "IFLO_SYS_EXECVE";
    break;
  case IFLO_SYS_SYS_CHDIR:
    rv = "IFLO_SYS_SYS_CHDIR";
    break;
  case IFLO_SYS_SYS_TIME:
    rv = "IFLO_SYS_SYS_TIME";
    break;
  case IFLO_SYS_SYS_MKNOD:
    rv = "IFLO_SYS_SYS_MKNOD";
    break;
  case IFLO_SYS_SYS_CHMOD:
    rv = "IFLO_SYS_SYS_CHMOD";
    break;
  case IFLO_SYS_SYS_LCHOWN:
    rv = "IFLO_SYS_SYS_LCHOWN";
    break;
  case IFLO_SYS_SYS_BREAK:
    rv = "IFLO_SYS_SYS_BREAK";
    break;
  case IFLO_SYS_STAT:
    rv = "IFLO_SYS_STAT";
    break;
  case IFLO_SYS_SYS_LSEEK:
    rv = "IFLO_SYS_SYS_LSEEK";
    break;
  case IFLO_SYS_SYS_GETPID:
    rv = "IFLO_SYS_SYS_GETPID";
    break;
  case IFLO_SYS_SYS_MOUNT:
    rv = "IFLO_SYS_SYS_MOUNT";
    break;
  case IFLO_SYS_SYS_UMOUNT:
    rv = "IFLO_SYS_SYS_UMOUNT";
    break;
  case IFLO_SYS_SYS_SETUID:
    rv = "IFLO_SYS_SYS_SETUID";
    break;
  case IFLO_SYS_SYS_GETUID:
    rv = "IFLO_SYS_SYS_GETUID";
    break;
  case IFLO_SYS_SYS_STIME:
    rv = "IFLO_SYS_SYS_STIME";
    break;
  case IFLO_SYS_SYS_PTRACE:
    rv = "IFLO_SYS_SYS_PTRACE";
    break;
  case IFLO_SYS_SYS_ALARM:
    rv = "IFLO_SYS_SYS_ALARM";
    break;
  case IFLO_SYS_SYS_OLDFSTAT:
    rv = "IFLO_SYS_SYS_OLDFSTAT";
    break;
  case IFLO_SYS_SYS_PAUSE:
    rv = "IFLO_SYS_SYS_PAUSE";
    break;
  case IFLO_SYS_SYS_UTIME:
    rv = "IFLO_SYS_SYS_UTIME";
    break;
  case IFLO_SYS_SYS_STTY:
    rv = "IFLO_SYS_SYS_STTY";
    break;
  case IFLO_SYS_SYS_GTTY:
    rv = "IFLO_SYS_SYS_GTTY";
    break;
  case IFLO_SYS_SYS_ACCESS:
    rv = "IFLO_SYS_SYS_ACCESS";
    break;
  case IFLO_SYS_SYS_NICE:
    rv = "IFLO_SYS_SYS_NICE";
    break;
  case IFLO_SYS_SYS_FTIME:
    rv = "IFLO_SYS_SYS_FTIME";
    break;
  case IFLO_SYS_SYS_SYNC:
    rv = "IFLO_SYS_SYS_SYNC";
    break;
  case IFLO_SYS_SYS_KILL:
    rv = "IFLO_SYS_SYS_KILL";
    break;
  case IFLO_SYS_SYS_RENAME:
    rv = "IFLO_SYS_SYS_RENAME";
    break;
  case IFLO_SYS_SYS_MKDIR:
    rv = "IFLO_SYS_SYS_MKDIR";
    break;
  case IFLO_SYS_SYS_RMDIR:
    rv = "IFLO_SYS_SYS_RMDIR";
    break;
  case IFLO_SYS_SYS_DUP:
    rv = "IFLO_SYS_SYS_DUP";
    break;
  case IFLO_SYS_PIPE:
    rv = "IFLO_SYS_PIPE";
    break;
  case IFLO_SYS_SYS_TIMES:
    rv = "IFLO_SYS_SYS_TIMES";
    break;
  case IFLO_SYS_SYS_PROF:
    rv = "IFLO_SYS_SYS_PROF";
    break;
  case IFLO_SYS_SYS_BRK:
    rv = "IFLO_SYS_SYS_BRK";
    break;
  case IFLO_SYS_SYS_SETGID:
    rv = "IFLO_SYS_SYS_SETGID";
    break;
  case IFLO_SYS_SYS_GETGID:
    rv = "IFLO_SYS_SYS_GETGID";
    break;
  case IFLO_SYS_SYS_SIGNAL:
    rv = "IFLO_SYS_SYS_SIGNAL";
    break;
  case IFLO_SYS_SYS_GETEUID:
    rv = "IFLO_SYS_SYS_GETEUID";
    break;
  case IFLO_SYS_SYS_GETEGID:
    rv = "IFLO_SYS_SYS_GETEGID";
    break;
  case IFLO_SYS_SYS_ACCT:
    rv = "IFLO_SYS_SYS_ACCT";
    break;
  case IFLO_SYS_UMOUNT2:
    rv = "IFLO_SYS_UMOUNT2";
    break;
  case IFLO_SYS_SYS_LOCK:
    rv = "IFLO_SYS_SYS_LOCK";
    break;
  case IFLO_SYS_SYS_IOCTL:
    rv = "IFLO_SYS_SYS_IOCTL";
    break;
  case IFLO_SYS_SYS_FCNTL:
    rv = "IFLO_SYS_SYS_FCNTL";
    break;
  case IFLO_SYS_SYS_MPX:
    rv = "IFLO_SYS_SYS_MPX";
    break;
  case IFLO_SYS_SYS_SETPGID:
    rv = "IFLO_SYS_SYS_SETPGID";
    break;
  case IFLO_SYS_SYS_ULIMIT:
    rv = "IFLO_SYS_SYS_ULIMIT";
    break;
  case IFLO_SYS_SYS_OLDOLDUNAME:
    rv = "IFLO_SYS_SYS_OLDOLDUNAME";
    break;
  case IFLO_SYS_SYS_UMASK:
    rv = "IFLO_SYS_SYS_UMASK";
    break;
  case IFLO_SYS_SYS_CHROOT:
    rv = "IFLO_SYS_SYS_CHROOT";
    break;
  case IFLO_SYS_SYS_USTAT:
    rv = "IFLO_SYS_SYS_USTAT";
    break;
  case IFLO_SYS_SYS_DUP2:
    rv = "IFLO_SYS_SYS_DUP2";
    break;
  case IFLO_SYS_SYS_GETPPID:
    rv = "IFLO_SYS_SYS_GETPPID";
    break;
  case IFLO_SYS_SYS_GETPGRP:
    rv = "IFLO_SYS_SYS_GETPGRP";
    break;
  case IFLO_SYS_SYS_SETSID:
    rv = "IFLO_SYS_SYS_SETSID";
    break;
  case IFLO_SYS_SYS_SIGACTION:
    rv = "IFLO_SYS_SYS_SIGACTION";
    break;
  case IFLO_SYS_SYS_SGETMASK:
    rv = "IFLO_SYS_SYS_SGETMASK";
    break;
  case IFLO_SYS_SYS_SSETMASK:
    rv = "IFLO_SYS_SYS_SSETMASK";
    break;
  case IFLO_SYS_SYS_SETREUID:
    rv = "IFLO_SYS_SYS_SETREUID";
    break;
  case IFLO_SYS_SYS_SETREGID:
    rv = "IFLO_SYS_SYS_SETREGID";
    break;
  case IFLO_SYS_SYS_SIGSUSPEND:
    rv = "IFLO_SYS_SYS_SIGSUSPEND";
    break;
  case IFLO_SYS_SYS_SIGPENDING:
    rv = "IFLO_SYS_SYS_SIGPENDING";
    break;
  case IFLO_SYS_SYS_SETHOSTNAME:
    rv = "IFLO_SYS_SYS_SETHOSTNAME";
    break;
  case IFLO_SYS_SYS_SETRLIMIT:
    rv = "IFLO_SYS_SYS_SETRLIMIT";
    break;
  case IFLO_SYS_SYS_GETRLIMIT:
    rv = "IFLO_SYS_SYS_GETRLIMIT";
    break;
  case IFLO_SYS_SYS_GETRUSAGE:
    rv = "IFLO_SYS_SYS_GETRUSAGE";
    break;
  case IFLO_SYS_SYS_GETTIMEOFDAY:
    rv = "IFLO_SYS_SYS_GETTIMEOFDAY";
    break;
  case IFLO_SYS_SYS_SETTIMEOFDAY:
    rv = "IFLO_SYS_SYS_SETTIMEOFDAY";
    break;
  case IFLO_SYS_SYS_GETGROUPS:
    rv = "IFLO_SYS_SYS_GETGROUPS";
    break;
  case IFLO_SYS_SYS_SETGROUPS:
    rv = "IFLO_SYS_SYS_SETGROUPS";
    break;
  case IFLO_SYS_SYS_SELECT:
    rv = "IFLO_SYS_SYS_SELECT";
    break;
  case IFLO_SYS_SYS_SYMLINK:
    rv = "IFLO_SYS_SYS_SYMLINK";
    break;
  case IFLO_SYS_OLDLSTAT:
    rv = "IFLO_SYS_OLDLSTAT";
    break;
  case IFLO_SYS_SYS_READLINK:
    rv = "IFLO_SYS_SYS_READLINK";
    break;
  case IFLO_SYS_SYS_USELIB:
    rv = "IFLO_SYS_SYS_USELIB";
    break;
  case IFLO_SYS_SYS_SWAPON:
    rv = "IFLO_SYS_SYS_SWAPON";
    break;
  case IFLO_SYS_SYS_REBOOT:
    rv = "IFLO_SYS_SYS_REBOOT";
    break;
  case IFLO_SYS_READDIR:
    rv = "IFLO_SYS_READDIR";
    break;
  case IFLO_SYS_MMAP:
    rv = "IFLO_SYS_MMAP";
    break;
  case IFLO_SYS_SYS_MUNMAP:
    rv = "IFLO_SYS_SYS_MUNMAP";
    break;
  case IFLO_SYS_SYS_TRUNCATE:
    rv = "IFLO_SYS_SYS_TRUNCATE";
    break;
  case IFLO_SYS_SYS_FTRUNCATE:
    rv = "IFLO_SYS_SYS_FTRUNCATE";
    break;
  case IFLO_SYS_SYS_FCHMOD:
    rv = "IFLO_SYS_SYS_FCHMOD";
    break;
  case IFLO_SYS_SYS_FCHOWN:
    rv = "IFLO_SYS_SYS_FCHOWN";
    break;
  case IFLO_SYS_SYS_GETPRIORITY:
    rv = "IFLO_SYS_SYS_GETPRIORITY";
    break;
  case IFLO_SYS_SYS_SETPRIORITY:
    rv = "IFLO_SYS_SYS_SETPRIORITY";
    break;
  case IFLO_SYS_SYS_PROFIL:
    rv = "IFLO_SYS_SYS_PROFIL";
    break;
  case IFLO_SYS_SYS_STATFS:
    rv = "IFLO_SYS_SYS_STATFS";
    break;
  case IFLO_SYS_SYS_FSTATFS:
    rv = "IFLO_SYS_SYS_FSTATFS";
    break;
  case IFLO_SYS_SYS_IOPERM:
    rv = "IFLO_SYS_SYS_IOPERM";
    break;
  case IFLO_UNUSED_394:
    rv = "IFLO_UNUSED_394";
    break;
  case IFLO_SYS_SYS_SYSLOG:
    rv = "IFLO_SYS_SYS_SYSLOG";
    break;
  case IFLO_SYS_SYS_SETITIMER:
    rv = "IFLO_SYS_SYS_SETITIMER";
    break;
  case IFLO_SYS_SYS_GETITIMER:
    rv = "IFLO_SYS_SYS_GETITIMER";
    break;
  case IFLO_SYS_SYS_STAT:
    rv = "IFLO_SYS_SYS_STAT";
    break;
  case IFLO_SYS_SYS_LSTAT:
    rv = "IFLO_SYS_SYS_LSTAT";
    break;
  case IFLO_SYS_SYS_FSTAT:
    rv = "IFLO_SYS_SYS_FSTAT";
    break;
  case IFLO_SYS_OLD_UNAME:
    rv = "IFLO_SYS_OLD_UNAME";
    break;
  case IFLO_SYS_IOPL:
    rv = "IFLO_SYS_IOPL";
    break;
  case IFLO_SYS_SYS_VHANGUP:
    rv = "IFLO_SYS_SYS_VHANGUP";
    break;
  case IFLO_SYS_IDLE:
    rv = "IFLO_SYS_IDLE";
    break;
  case IFLO_SYS_VM86OLD:
    rv = "IFLO_SYS_VM86OLD";
    break;
  case IFLO_SYS_SYS_WAIT4:
    rv = "IFLO_SYS_SYS_WAIT4";
    break;
  case IFLO_SYS_SYS_SWAPOFF:
    rv = "IFLO_SYS_SYS_SWAPOFF";
    break;
  case IFLO_SYS_SYS_SYSINFO:
    rv = "IFLO_SYS_SYS_SYSINFO";
    break;
  case IFLO_SYS_IPC:
    rv = "IFLO_SYS_IPC";
    break;
  case IFLO_SYS_SYS_FSYNC:
    rv = "IFLO_SYS_SYS_FSYNC";
    break;
  case IFLO_SYS_SIGRETURN:
    rv = "IFLO_SYS_SIGRETURN";
    break;
  case IFLO_SYS_CLONE:
    rv = "IFLO_SYS_CLONE";
    break;
  case IFLO_SYS_SYS_SETDOMAINNAME:
    rv = "IFLO_SYS_SYS_SETDOMAINNAME";
    break;
  case IFLO_SYS_UNAME:
    rv = "IFLO_SYS_UNAME";
    break;
  case IFLO_SYS_MODIFY_LDT:
    rv = "IFLO_SYS_MODIFY_LDT";
    break;
  case IFLO_SYS_SYS_ADJTIMEX:
    rv = "IFLO_SYS_SYS_ADJTIMEX";
    break;
  case IFLO_SYS_SYS_MPROTECT:
    rv = "IFLO_SYS_SYS_MPROTECT";
    break;
  case IFLO_SYS_SYS_SIGPROCMASK:
    rv = "IFLO_SYS_SYS_SIGPROCMASK";
    break;
  case IFLO_SYS_SYS_CREATE_MODULE:
    rv = "IFLO_SYS_SYS_CREATE_MODULE";
    break;
  case IFLO_SYS_SYS_INIT_MODULE:
    rv = "IFLO_SYS_SYS_INIT_MODULE";
    break;
  case IFLO_SYS_SYS_DELETE_MODULE:
    rv = "IFLO_SYS_SYS_DELETE_MODULE";
    break;
  case IFLO_SYS_SYS_GET_KERNEL_SYMS:
    rv = "IFLO_SYS_SYS_GET_KERNEL_SYMS";
    break;
  case IFLO_SYS_SYS_QUOTACTL:
    rv = "IFLO_SYS_SYS_QUOTACTL";
    break;
  case IFLO_SYS_SYS_GETPGID:
    rv = "IFLO_SYS_SYS_GETPGID";
    break;
  case IFLO_SYS_SYS_FCHDIR:
    rv = "IFLO_SYS_SYS_FCHDIR";
    break;
  case IFLO_SYS_SYS_BDFLUSH:
    rv = "IFLO_SYS_SYS_BDFLUSH";
    break;
  case IFLO_SYS_SYS_SYSFS:
    rv = "IFLO_SYS_SYS_SYSFS";
    break;
  case IFLO_SYS_SYS_PERSONALITY:
    rv = "IFLO_SYS_SYS_PERSONALITY";
    break;
  case IFLO_SYS_SYS_AFS_SYSCALL:
    rv = "IFLO_SYS_SYS_AFS_SYSCALL";
    break;
  case IFLO_SYS_SYS_SETFSUID:
    rv = "IFLO_SYS_SYS_SETFSUID";
    break;
  case IFLO_SYS_SYS_SETFSGID:
    rv = "IFLO_SYS_SYS_SETFSGID";
    break;
  case IFLO_SYS_SYS__LLSEEK:
    rv = "IFLO_SYS_SYS__LLSEEK";
    break;
  case IFLO_SYS_SYS_GETDENTS:
    rv = "IFLO_SYS_SYS_GETDENTS";
    break;
  case IFLO_SYS_SYS__NEWSELECT:
    rv = "IFLO_SYS_SYS__NEWSELECT";
    break;
  case IFLO_SYS_SYS_FLOCK:
    rv = "IFLO_SYS_SYS_FLOCK";
    break;
  case IFLO_SYS_SYS_MSYNC:
    rv = "IFLO_SYS_SYS_MSYNC";
    break;
  case IFLO_SYS_SYS_READV:
    rv = "IFLO_SYS_SYS_READV";
    break;
  case IFLO_SYS_SYS_WRITEV:
    rv = "IFLO_SYS_SYS_WRITEV";
    break;
  case IFLO_SYS_SYS_GETSID:
    rv = "IFLO_SYS_SYS_GETSID";
    break;
  case IFLO_SYS_SYS_FDATASYNC:
    rv = "IFLO_SYS_SYS_FDATASYNC";
    break;
  case IFLO_SYS_SYS__SYSCTL:
    rv = "IFLO_SYS_SYS__SYSCTL";
    break;
  case IFLO_SYS_SYS_MLOCK:
    rv = "IFLO_SYS_SYS_MLOCK";
    break;
  case IFLO_SYS_SYS_MUNLOCK:
    rv = "IFLO_SYS_SYS_MUNLOCK";
    break;
  case IFLO_SYS_SYS_MLOCKALL:
    rv = "IFLO_SYS_SYS_MLOCKALL";
    break;
  case IFLO_SYS_SYS_MUNLOCKALL:
    rv = "IFLO_SYS_SYS_MUNLOCKALL";
    break;
  case IFLO_SYS_SYS_SCHED_SETPARAM:
    rv = "IFLO_SYS_SYS_SCHED_SETPARAM";
    break;
  case IFLO_SYS_SYS_SCHED_GETPARAM:
    rv = "IFLO_SYS_SYS_SCHED_GETPARAM";
    break;
  case IFLO_SYS_SYS_SCHED_SETSCHEDULER:
    rv = "IFLO_SYS_SYS_SCHED_SETSCHEDULER";
    break;
  case IFLO_SYS_SYS_SCHED_GETSCHEDULER:
    rv = "IFLO_SYS_SYS_SCHED_GETSCHEDULER";
    break;
  case IFLO_SYS_SYS_SCHED_YIELD:
    rv = "IFLO_SYS_SYS_SCHED_YIELD";
    break;
  case IFLO_SYS_SYS_SCHED_GET_PRIORITY_MAX:
    rv = "IFLO_SYS_SYS_SCHED_GET_PRIORITY_MAX";
    break;
  case IFLO_SYS_SYS_SCHED_GET_PRIORITY_MIN:
    rv = "IFLO_SYS_SYS_SCHED_GET_PRIORITY_MIN";
    break;
  case IFLO_SYS_SYS_SCHED_RR_GET_INTERVAL:
    rv = "IFLO_SYS_SYS_SCHED_RR_GET_INTERVAL";
    break;
  case IFLO_SYS_SYS_NANOSLEEP:
    rv = "IFLO_SYS_SYS_NANOSLEEP";
    break;
  case IFLO_SYS_SYS_MREMAP:
    rv = "IFLO_SYS_SYS_MREMAP";
    break;
  case IFLO_SYS_SYS_SETRESUID:
    rv = "IFLO_SYS_SYS_SETRESUID";
    break;
  case IFLO_SYS_SYS_GETRESUID16:
    rv = "IFLO_SYS_SYS_GETRESUID16";
    break;
  case IFLO_SYS_SYS_VM86:
    rv = "IFLO_SYS_SYS_VM86";
    break;
  case IFLO_SYS_SYS_QUERY_MODULE:
    rv = "IFLO_SYS_SYS_QUERY_MODULE";
    break;
  case IFLO_SYS_SYS_POLL:
    rv = "IFLO_SYS_SYS_POLL";
    break;
  case IFLO_SYS_SYS_NFSSERVCTL:
    rv = "IFLO_SYS_SYS_NFSSERVCTL";
    break;
  case IFLO_SYS_SETRESGID:
    rv = "IFLO_SYS_SETRESGID";
    break;
  case IFLO_SYS_SYS_GETRESGID:
    rv = "IFLO_SYS_SYS_GETRESGID";
    break;
  case IFLO_SYS_SYS_PRCTL:
    rv = "IFLO_SYS_SYS_PRCTL";
    break;
  case IFLO_SYS_RT_SIGRETURN:
    rv = "IFLO_SYS_RT_SIGRETURN";
    break;
  case IFLO_SYS_SIGACTION:
    rv = "IFLO_SYS_SIGACTION";
    break;
  case IFLO_SYS_SYS_RT_SIGPROCMASK:
    rv = "IFLO_SYS_SYS_RT_SIGPROCMASK";
    break;
  case IFLO_SYS_SYS_RT_SIGPENDING:
    rv = "IFLO_SYS_SYS_RT_SIGPENDING";
    break;
  case IFLO_SYS_SYS_RT_SIGTIMEDWAIT:
    rv = "IFLO_SYS_SYS_RT_SIGTIMEDWAIT";
    break;
  case IFLO_SYS_SYS_RT_SIGQUEUEINFO:
    rv = "IFLO_SYS_SYS_RT_SIGQUEUEINFO";
    break;
  case IFLO_SYS_SIGSUSPEND:
    rv = "IFLO_SYS_SIGSUSPEND";
    break;
  case IFLO_SYS_SYS_PREAD64:
    rv = "IFLO_SYS_SYS_PREAD64";
    break;
  case IFLO_SYS_SYS_PWRITE64:
    rv = "IFLO_SYS_SYS_PWRITE64";
    break;
  case IFLO_SYS_SYS_CHOWN:
    rv = "IFLO_SYS_SYS_CHOWN";
    break;
  case IFLO_SYS_SYS_GETCWD:
    rv = "IFLO_SYS_SYS_GETCWD";
    break;
  case IFLO_SYS_SYS_CAPGET:
    rv = "IFLO_SYS_SYS_CAPGET";
    break;
  case IFLO_SYS_SYS_CAPSET:
    rv = "IFLO_SYS_SYS_CAPSET";
    break;
  case IFLO_SYS_SIGALTSTACK:
    rv = "IFLO_SYS_SIGALTSTACK";
    break;
  case IFLO_SYS_SYS_SENDFILE:
    rv = "IFLO_SYS_SYS_SENDFILE";
    break;
  case IFLO_SYS_SYS_GETPMSG:
    rv = "IFLO_SYS_SYS_GETPMSG";
    break;
  case IFLO_SYS_SYS_PUTPMSG:
    rv = "IFLO_SYS_SYS_PUTPMSG";
    break;
  case IFLO_SYS_VFORK:
    rv = "IFLO_SYS_VFORK";
    break;
  case IFLO_SYS_GETRLIMIT:
    rv = "IFLO_SYS_GETRLIMIT";
    break;
  case IFLO_SYS_MMAP2:
    rv = "IFLO_SYS_MMAP2";
    break;
  case IFLO_SYS_SYS_TRUNCATE64:
    rv = "IFLO_SYS_SYS_TRUNCATE64";
    break;
  case IFLO_SYS_SYS_FTRUNCATE64:
    rv = "IFLO_SYS_SYS_FTRUNCATE64";
    break;
  case IFLO_SYS_SYS_STAT64:
    rv = "IFLO_SYS_SYS_STAT64";
    break;
  case IFLO_SYS_SYS_LSTAT64:
    rv = "IFLO_SYS_SYS_LSTAT64";
    break;
  case IFLO_SYS_SYS_FSTAT64:
    rv = "IFLO_SYS_SYS_FSTAT64";
    break;
  case IFLO_SYS_LCHOWN:
    rv = "IFLO_SYS_LCHOWN";
    break;
  case IFLO_SYS_GETUID:
    rv = "IFLO_SYS_GETUID";
    break;
  case IFLO_SYS_GETGID:
    rv = "IFLO_SYS_GETGID";
    break;
  case IFLO_SYS_GETEUID:
    rv = "IFLO_SYS_GETEUID";
    break;
  case IFLO_SYS_GETEGID:
    rv = "IFLO_SYS_GETEGID";
    break;
  case IFLO_SYS_SETREUID:
    rv = "IFLO_SYS_SETREUID";
    break;
  case IFLO_SYS_SETREGID:
    rv = "IFLO_SYS_SETREGID";
    break;
  case IFLO_SYS_GETGROUPS:
    rv = "IFLO_SYS_GETGROUPS";
    break;
  case IFLO_SYS_SETGROUPS:
    rv = "IFLO_SYS_SETGROUPS";
    break;
  case IFLO_SYS_FCHOWN:
    rv = "IFLO_SYS_FCHOWN";
    break;
  case IFLO_SYS_SETRESUID:
    rv = "IFLO_SYS_SETRESUID";
    break;
  case IFLO_SYS_GETRESUID:
    rv = "IFLO_SYS_GETRESUID";
    break;
  case IFLO_SYS_SETRESGID32:
    rv = "IFLO_SYS_SETRESGID32";
    break;
  case IFLO_SYS_GETRESGID:
    rv = "IFLO_SYS_GETRESGID";
    break;
  case IFLO_SYS_CHOWN:
    rv = "IFLO_SYS_CHOWN";
    break;
  case IFLO_SYS_SETUID:
    rv = "IFLO_SYS_SETUID";
    break;
  case IFLO_SYS_SETGID:
    rv = "IFLO_SYS_SETGID";
    break;
  case IFLO_SYS_SETFSUID:
    rv = "IFLO_SYS_SETFSUID";
    break;
  case IFLO_SYS_SETFSGID:
    rv = "IFLO_SYS_SETFSGID";
    break;
  case IFLO_SYS_SYS_PIVOT_ROOT:
    rv = "IFLO_SYS_SYS_PIVOT_ROOT";
    break;
  case IFLO_SYS_SYS_MINCORE:
    rv = "IFLO_SYS_SYS_MINCORE";
    break;
  case IFLO_SYS_SYS_MADVISE:
    rv = "IFLO_SYS_SYS_MADVISE";
    break;
  case IFLO_SYS_SYS_GETDENTS64:
    rv = "IFLO_SYS_SYS_GETDENTS64";
    break;
  case IFLO_SYS_SYS_FCNTL64:
    rv = "IFLO_SYS_SYS_FCNTL64";
    break;
  case IFLO_UNUSED_514:
    rv = "IFLO_UNUSED_514";
    break;
  case IFLO_UNUSED_515:
    rv = "IFLO_UNUSED_515";
    break;
  case IFLO_SYS_SYS_GETTID:
    rv = "IFLO_SYS_SYS_GETTID";
    break;
  case IFLO_SYS_SYS_READAHEAD:
    rv = "IFLO_SYS_SYS_READAHEAD";
    break;
  case IFLO_SYS_SYS_SETXATTR:
    rv = "IFLO_SYS_SYS_SETXATTR";
    break;
  case IFLO_SYS_SYS_LSETXATTR:
    rv = "IFLO_SYS_SYS_LSETXATTR";
    break;
  case IFLO_SYS_SYS_FSETXATTR:
    rv = "IFLO_SYS_SYS_FSETXATTR";
    break;
  case IFLO_SYS_SYS_GETXATTR:
    rv = "IFLO_SYS_SYS_GETXATTR";
    break;
  case IFLO_SYS_SYS_LGETXATTR:
    rv = "IFLO_SYS_SYS_LGETXATTR";
    break;
  case IFLO_SYS_SYS_FGETXATTR:
    rv = "IFLO_SYS_SYS_FGETXATTR";
    break;
  case IFLO_SYS_SYS_LISTXATTR:
    rv = "IFLO_SYS_SYS_LISTXATTR";
    break;
  case IFLO_SYS_SYS_LLISTXATTR:
    rv = "IFLO_SYS_SYS_LLISTXATTR";
    break;
  case IFLO_SYS_SYS_FLISTXATTR:
    rv = "IFLO_SYS_SYS_FLISTXATTR";
    break;
  case IFLO_SYS_SYS_REMOVEXATTR:
    rv = "IFLO_SYS_SYS_REMOVEXATTR";
    break;
  case IFLO_SYS_SYS_LREMOVEXATTR:
    rv = "IFLO_SYS_SYS_LREMOVEXATTR";
    break;
  case IFLO_SYS_SYS_FREMOVEXATTR:
    rv = "IFLO_SYS_SYS_FREMOVEXATTR";
    break;
  case IFLO_SYS_SYS_TKILL:
    rv = "IFLO_SYS_SYS_TKILL";
    break;
  case IFLO_SYS_SYS_SENDFILE64:
    rv = "IFLO_SYS_SYS_SENDFILE64";
    break;
  case IFLO_SYS_SYS_FUTEX:
    rv = "IFLO_SYS_SYS_FUTEX";
    break;
  case IFLO_SYS_SYS_SCHED_SETAFFINITY:
    rv = "IFLO_SYS_SYS_SCHED_SETAFFINITY";
    break;
  case IFLO_SYS_SYS_SCHED_GETAFFINITY:
    rv = "IFLO_SYS_SYS_SCHED_GETAFFINITY";
    break;
  case IFLO_SYS_SET_THREAD_AREA:
    rv = "IFLO_SYS_SET_THREAD_AREA";
    break;
  case IFLO_SYS_GET_THREAD_AREA:
    rv = "IFLO_SYS_GET_THREAD_AREA";
    break;
  case IFLO_SYS_SYS_IO_SETUP:
    rv = "IFLO_SYS_SYS_IO_SETUP";
    break;
  case IFLO_SYS_SYS_IO_DESTROY:
    rv = "IFLO_SYS_SYS_IO_DESTROY";
    break;
  case IFLO_SYS_SYS_IO_GETEVENTS:
    rv = "IFLO_SYS_SYS_IO_GETEVENTS";
    break;
  case IFLO_SYS_SYS_IO_SUBMIT:
    rv = "IFLO_SYS_SYS_IO_SUBMIT";
    break;
  case IFLO_SYS_SYS_IO_CANCEL:
    rv = "IFLO_SYS_SYS_IO_CANCEL";
    break;
  case IFLO_SYS_SYS_FADVISE64:
    rv = "IFLO_SYS_SYS_FADVISE64";
    break;
  case IFLO_UNUSED_543:
    rv = "IFLO_UNUSED_543";
    break;
  case IFLO_SYS_SYS_EXIT_GROUP:
    rv = "IFLO_SYS_SYS_EXIT_GROUP";
    break;
  case IFLO_SYS_SYS_LOOKUP_DCOOKIE:
    rv = "IFLO_SYS_SYS_LOOKUP_DCOOKIE";
    break;
  case IFLO_SYS_SYS_EPOLL_CREATE:
    rv = "IFLO_SYS_SYS_EPOLL_CREATE";
    break;
  case IFLO_SYS_SYS_EPOLL_CTL:
    rv = "IFLO_SYS_SYS_EPOLL_CTL";
    break;
  case IFLO_SYS_SYS_EPOLL_WAIT:
    rv = "IFLO_SYS_SYS_EPOLL_WAIT";
    break;
  case IFLO_SYS_SYS_REMAP_FILE_PAGES:
    rv = "IFLO_SYS_SYS_REMAP_FILE_PAGES";
    break;
  case IFLO_SYS_SYS_SET_TID_ADDRESS:
    rv = "IFLO_SYS_SYS_SET_TID_ADDRESS";
    break;
  case IFLO_SYS_SYS_TIMER_CREATE:
    rv = "IFLO_SYS_SYS_TIMER_CREATE";
    break;
  case IFLO_SYS_SYS_TIMER_SETTIME:
    rv = "IFLO_SYS_SYS_TIMER_SETTIME";
    break;
  case IFLO_SYS_SYS_TIMER_GETTIME:
    rv = "IFLO_SYS_SYS_TIMER_GETTIME";
    break;
  case IFLO_SYS_SYS_TIMER_GETOVERRUN:
    rv = "IFLO_SYS_SYS_TIMER_GETOVERRUN";
    break;
  case IFLO_SYS_SYS_TIMER_DELETE:
    rv = "IFLO_SYS_SYS_TIMER_DELETE";
    break;
  case IFLO_SYS_SYS_CLOCK_SETTIME:
    rv = "IFLO_SYS_SYS_CLOCK_SETTIME";
    break;
  case IFLO_SYS_SYS_CLOCK_GETTIME:
    rv = "IFLO_SYS_SYS_CLOCK_GETTIME";
    break;
  case IFLO_SYS_SYS_CLOCK_GETRES:
    rv = "IFLO_SYS_SYS_CLOCK_GETRES";
    break;
  case IFLO_SYS_SYS_CLOCK_NANOSLEEP:
    rv = "IFLO_SYS_SYS_CLOCK_NANOSLEEP";
    break;
  case IFLO_SYS_SYS_STATFS64:
    rv = "IFLO_SYS_SYS_STATFS64";
    break;
  case IFLO_SYS_SYS_FSTATFS64:
    rv = "IFLO_SYS_SYS_FSTATFS64";
    break;
  case IFLO_SYS_SYS_TGKILL:
    rv = "IFLO_SYS_SYS_TGKILL";
    break;
  case IFLO_SYS_SYS_UTIMES:
    rv = "IFLO_SYS_SYS_UTIMES";
    break;
  case IFLO_SYS_SYS_FADVISE64_64:
    rv = "IFLO_SYS_SYS_FADVISE64_64";
    break;
  case IFLO_SYS_SYS_VSERVER:
    rv = "IFLO_SYS_SYS_VSERVER";
    break;
  case IFLO_SYS_SYS_MBIND:
    rv = "IFLO_SYS_SYS_MBIND";
    break;
  case IFLO_SYS_SYS_GET_MEMPOLICY:
    rv = "IFLO_SYS_SYS_GET_MEMPOLICY";
    break;
  case IFLO_SYS_SYS_SET_MEMPOLICY:
    rv = "IFLO_SYS_SYS_SET_MEMPOLICY";
    break;
  case IFLO_SYS_SYS_MQ_OPEN:
    rv = "IFLO_SYS_SYS_MQ_OPEN";
    break;
  case IFLO_SYS_SYS_MQ_UNLINK:
    rv = "IFLO_SYS_SYS_MQ_UNLINK";
    break;
  case IFLO_SYS_SYS_MQ_TIMEDSEND:
    rv = "IFLO_SYS_SYS_MQ_TIMEDSEND";
    break;
  case IFLO_SYS_SYS_MQ_TIMEDRECEIVE:
    rv = "IFLO_SYS_SYS_MQ_TIMEDRECEIVE";
    break;
  case IFLO_SYS_SYS_MQ_NOTIFY:
    rv = "IFLO_SYS_SYS_MQ_NOTIFY";
    break;
  case IFLO_SYS_SYS_MQ_GETSETATTR:
    rv = "IFLO_SYS_SYS_MQ_GETSETATTR";
    break;
  case IFLO_SYS_SYS_KEXEC_LOAD:
    rv = "IFLO_SYS_SYS_KEXEC_LOAD";
    break;
  case IFLO_SYS_SYS_WAITID:
    rv = "IFLO_SYS_SYS_WAITID";
    break;
  case IFLO_SYS_SYS_SETALTROOT:
    rv = "IFLO_SYS_SYS_SETALTROOT";
    break;
  case IFLO_SYS_SYS_ADD_KEY:
    rv = "IFLO_SYS_SYS_ADD_KEY";
    break;
  case IFLO_SYS_SYS_REQUEST_KEY:
    rv = "IFLO_SYS_SYS_REQUEST_KEY";
    break;
  case IFLO_SYS_SYS_KEYCTL:
    rv = "IFLO_SYS_SYS_KEYCTL";
    break;
  case IFLO_SYS_SYS_IOPRIO_SET:
    rv = "IFLO_SYS_SYS_IOPRIO_SET";
    break;
  case IFLO_SYS_SYS_IOPRIO_GET:
    rv = "IFLO_SYS_SYS_IOPRIO_GET";
    break;
  case IFLO_SYS_SYS_INOTIFY_INIT:
    rv = "IFLO_SYS_SYS_INOTIFY_INIT";
    break;
  case IFLO_SYS_SYS_INOTIFY_ADD_WATCH:
    rv = "IFLO_SYS_SYS_INOTIFY_ADD_WATCH";
    break;
  case IFLO_SYS_SYS_INOTIFY_RM_WATCH:
    rv = "IFLO_SYS_SYS_INOTIFY_RM_WATCH";
    break;
  case IFLO_SYS_SYS_MIGRATE_PAGES:
    rv = "IFLO_SYS_SYS_MIGRATE_PAGES";
    break;
  case IFLO_SYS_SYS_OPENAT:
    rv = "IFLO_SYS_SYS_OPENAT";
    break;
  case IFLO_SYS_SYS_MKDIRAT:
    rv = "IFLO_SYS_SYS_MKDIRAT";
    break;
  case IFLO_SYS_SYS_MKNODAT:
    rv = "IFLO_SYS_SYS_MKNODAT";
    break;
  case IFLO_SYS_SYS_FCHOWNAT:
    rv = "IFLO_SYS_SYS_FCHOWNAT";
    break;
  case IFLO_SYS_SYS_FUTIMESAT:
    rv = "IFLO_SYS_SYS_FUTIMESAT";
    break;
  case IFLO_SYS_SYS_FSTATAT64:
    rv = "IFLO_SYS_SYS_FSTATAT64";
    break;
  case IFLO_SYS_SYS_UNLINKAT:
    rv = "IFLO_SYS_SYS_UNLINKAT";
    break;
  case IFLO_SYS_SYS_RENAMEAT:
    rv = "IFLO_SYS_SYS_RENAMEAT";
    break;
  case IFLO_SYS_SYS_LINKAT:
    rv = "IFLO_SYS_SYS_LINKAT";
    break;
  case IFLO_SYS_SYS_SYMLINKAT:
    rv = "IFLO_SYS_SYS_SYMLINKAT";
    break;
  case IFLO_SYS_SYS_READLINKAT:
    rv = "IFLO_SYS_SYS_READLINKAT";
    break;
  case IFLO_SYS_SYS_FCHMODAT:
    rv = "IFLO_SYS_SYS_FCHMODAT";
    break;
  case IFLO_SYS_SYS_FACCESSAT:
    rv = "IFLO_SYS_SYS_FACCESSAT";
    break;
  case IFLO_SYS_PSELECT:
    rv = "IFLO_SYS_PSELECT";
    break;
  case IFLO_SYS_PPOLL:
    rv = "IFLO_SYS_PPOLL";
    break;
  case IFLO_SYS_SYS_UNSHARE:
    rv = "IFLO_SYS_SYS_UNSHARE";
    break;
  case IFLO_SYS_SYS_SET_ROBUST_LIST:
    rv = "IFLO_SYS_SYS_SET_ROBUST_LIST";
    break;
  case IFLO_SYS_SYS_GET_ROBUST_LIST:
    rv = "IFLO_SYS_SYS_GET_ROBUST_LIST";
    break;
  case IFLO_SYS_SYS_SPLICE:
    rv = "IFLO_SYS_SYS_SPLICE";
    break;
  case IFLO_SYS_SYS_SYNC_FILE_RANGE:
    rv = "IFLO_SYS_SYS_SYNC_FILE_RANGE";
    break;
  case IFLO_SYS_SYS_TEE:
    rv = "IFLO_SYS_SYS_TEE";
    break;
  case IFLO_SYS_SYS_VMSPLICE:
    rv = "IFLO_SYS_SYS_VMSPLICE";
    break;
  case IFLO_SYS_SYS_MOVE_PAGES:
    rv = "IFLO_SYS_SYS_MOVE_PAGES";
    break;
  case IFLO_SYS_SYS_GETCPU:
    rv = "IFLO_SYS_SYS_GETCPU";
    break;
  case IFLO_SYS_SYS_EPOLL_WAIT_ANOTHER:
    rv = "IFLO_SYS_SYS_EPOLL_WAIT_ANOTHER";
    break;
  case IFLO_SYS_SYS_UTIMENSAT:
    rv = "IFLO_SYS_SYS_UTIMENSAT";
    break;
  case IFLO_SYS_SYS_SIGNALFD:
    rv = "IFLO_SYS_SYS_SIGNALFD";
    break;
  case IFLO_SYS_SYS_TIMERFD_CREATE:
    rv = "IFLO_SYS_SYS_TIMERFD_CREATE";
    break;
  case IFLO_SYS_SYS_EVENTFD:
    rv = "IFLO_SYS_SYS_EVENTFD";
    break;
  case IFLO_SYS_SYS_FALLOCATE:
    rv = "IFLO_SYS_SYS_FALLOCATE";
    break;
  case IFLO_SYS_SYS_TIMERFD_SETTIME:
    rv = "IFLO_SYS_SYS_TIMERFD_SETTIME";
    break;
  case IFLO_SYS_SYS_TIMERFD_GETTIME:
    rv = "IFLO_SYS_SYS_TIMERFD_GETTIME";
    break;
  case IFLO_SYS_SYS_SIGNALFD4:
    rv = "IFLO_SYS_SYS_SIGNALFD4";
    break;
  case IFLO_SYS_SYS_EVENTFD2:
    rv = "IFLO_SYS_SYS_EVENTFD2";
    break;
  case IFLO_SYS_SYS_EPOLL_CREATE1:
    rv = "IFLO_SYS_SYS_EPOLL_CREATE1";
    break;
  case IFLO_SYS_SYS_DUP3:
    rv = "IFLO_SYS_SYS_DUP3";
    break;
  case IFLO_SYS_SYS_PIPE2:
    rv = "IFLO_SYS_SYS_PIPE2";
    break;
  case IFLO_SYS_SYS_INOTIFY_INIT1:
    rv = "IFLO_SYS_SYS_INOTIFY_INIT1";
    break;
  case IFLO_SYS_SOCKETCALLS_START:
    rv = "IFLO_SYS_SOCKETCALLS_START";
    break;
  case IFLO_SYS_SOCKETCALL_SOCKET:
    rv = "IFLO_SYS_SOCKETCALL_SOCKET";
    break;
  case IFLO_SYS_SOCKETCALL_BIND_PF_LOCAL:
    rv = "IFLO_SYS_SOCKETCALL_BIND_PF_LOCAL";
    break;
  case IFLO_SYS_SOCKETCALL_BIND_PF_INET:
    rv = "IFLO_SYS_SOCKETCALL_BIND_PF_INET";
    break;
  case IFLO_SYS_SOCKETCALL_BIND_PF_NETLINK:
    rv = "IFLO_SYS_SOCKETCALL_BIND_PF_NETLINK";
    break;
  case IFLO_SYS_SOCKETCALL_BIND_PF_PACKET:
    rv = "IFLO_SYS_SOCKETCALL_BIND_PF_PACKET";
    break;
  case IFLO_SYS_SOCKETCALL_BIND_ELSE:
    rv = "IFLO_SYS_SOCKETCALL_BIND_ELSE";
    break;
  case IFLO_SYS_SOCKETCALL_CONNECT_PF_LOCAL:
    rv = "IFLO_SYS_SOCKETCALL_CONNECT_PF_LOCAL";
    break;
  case IFLO_SYS_SOCKETCALL_CONNECT_PF_INET:
    rv = "IFLO_SYS_SOCKETCALL_CONNECT_PF_INET";
    break;
  case IFLO_SYS_SOCKETCALL_CONNECT_PF_ELSE:
    rv = "IFLO_SYS_SOCKETCALL_CONNECT_PF_ELSE";
    break;
  case IFLO_SYS_SOCKETCALL_LISTEN:
    rv = "IFLO_SYS_SOCKETCALL_LISTEN";
    break;
  case IFLO_SYS_SOCKETCALL_ACCEPT:
    rv = "IFLO_SYS_SOCKETCALL_ACCEPT";
    break;
  case IFLO_SYS_SOCKETCALL_GETSOCKNAME:
    rv = "IFLO_SYS_SOCKETCALL_GETSOCKNAME";
    break;
  case IFLO_SYS_SOCKETCALL_GETPEERNAME:
    rv = "IFLO_SYS_SOCKETCALL_GETPEERNAME";
    break;
  case IFLO_SYS_SOCKETCALL_SOCKETPAIR:
    rv = "IFLO_SYS_SOCKETCALL_SOCKETPAIR";
    break;
  case IFLO_SYS_SOCKETCALL_SEND:
    rv = "IFLO_SYS_SOCKETCALL_SEND";
    break;
  case IFLO_SYS_SOCKETCALL_RECV:
    rv = "IFLO_SYS_SOCKETCALL_RECV";
    break;
  case IFLO_SYS_SOCKETCALL_SENDTO_PF_LOCAL:
    rv = "IFLO_SYS_SOCKETCALL_SENDTO_PF_LOCAL";
    break;
  case IFLO_SYS_SOCKETCALL_SENDTO_PF_INET:
    rv = "IFLO_SYS_SOCKETCALL_SENDTO_PF_INET";
    break;
  case IFLO_SYS_SOCKETCALL_SENDTO_PF_ELSE:
    rv = "IFLO_SYS_SOCKETCALL_SENDTO_PF_ELSE";
    break;
  case IFLO_SYS_SOCKETCALL_RECVFROM:
    rv = "IFLO_SYS_SOCKETCALL_RECVFROM";
    break;
  case IFLO_SYS_SOCKETCALL_SHUTDOWN:
    rv = "IFLO_SYS_SOCKETCALL_SHUTDOWN";
    break;
  case IFLO_SYS_SOCKETCALL_SETSOCKOPT:
    rv = "IFLO_SYS_SOCKETCALL_SETSOCKOPT";
    break;
  case IFLO_SYS_SOCKETCALL_GETSOCKOPT:
    rv = "IFLO_SYS_SOCKETCALL_GETSOCKOPT";
    break;
  case IFLO_SYS_SOCKETCALL_SENDMSG:
    rv = "IFLO_SYS_SOCKETCALL_SENDMSG";
    break;
  case IFLO_SYS_SOCKETCALL_RECVMSG:
    rv = "IFLO_SYS_SOCKETCALL_RECVMSG";
    break;
  case IFLO_DUMMY_LAST:
    rv = "IFLO_DUMMY_LAST";
    break;
  }
  return rv;
}
