// NB: This code is auto-generated by make_iferret_code.pl. 
// It contains a large number of functions that write an op plus
// a standard argument list.
static inline void iferret_log_op_write_0(
  iferret_log_op_enum_t op_num)
{
  iferret_log_op_write_prologue(op_num);
}

static inline void iferret_log_info_flow_op_write_0(
  iferret_log_op_enum_t op_num)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
#endif
}

static inline void iferret_log_socketcall_op_write_0(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
#endif
}

static inline void iferret_log_syscall_op_write_0(
  iferret_syscall_t *sc)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
#endif
}

static inline void iferret_log_sysret_op_write_0(
  iferret_log_op_enum_t op_num)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
#endif
}

static inline void iferret_log_op_write_1(
  iferret_log_op_enum_t op_num,
  uint8_t a1)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_1(a1);
}

static inline void iferret_log_info_flow_op_write_1(
  iferret_log_op_enum_t op_num,
  uint8_t a1)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_1(a1);
#endif
}

static inline void iferret_log_socketcall_op_write_1(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint8_t a1)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_1(a1);
#endif
}

static inline void iferret_log_syscall_op_write_1(
  iferret_syscall_t *sc,
  uint8_t a1)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_1(a1);
#endif
}

static inline void iferret_log_sysret_op_write_1(
  iferret_log_op_enum_t op_num,
  uint8_t a1)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_1(a1);
#endif
}

static inline void iferret_log_op_write_18(
  iferret_log_op_enum_t op_num,
  uint8_t a1,
  uint64_t a2)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_1(a1);
  iferret_log_write_8(a2);
}

static inline void iferret_log_info_flow_op_write_18(
  iferret_log_op_enum_t op_num,
  uint8_t a1,
  uint64_t a2)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_1(a1);
  iferret_log_write_8(a2);
#endif
}

static inline void iferret_log_socketcall_op_write_18(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint8_t a1,
  uint64_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_1(a1);
  iferret_log_write_8(a2);
#endif
}

static inline void iferret_log_syscall_op_write_18(
  iferret_syscall_t *sc,
  uint8_t a1,
  uint64_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_1(a1);
  iferret_log_write_8(a2);
#endif
}

static inline void iferret_log_sysret_op_write_18(
  iferret_log_op_enum_t op_num,
  uint8_t a1,
  uint64_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_1(a1);
  iferret_log_write_8(a2);
#endif
}

static inline void iferret_log_op_write_188(
  iferret_log_op_enum_t op_num,
  uint8_t a1,
  uint64_t a2,
  uint64_t a3)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_1(a1);
  iferret_log_write_8(a2);
  iferret_log_write_8(a3);
}

static inline void iferret_log_info_flow_op_write_188(
  iferret_log_op_enum_t op_num,
  uint8_t a1,
  uint64_t a2,
  uint64_t a3)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_1(a1);
  iferret_log_write_8(a2);
  iferret_log_write_8(a3);
#endif
}

static inline void iferret_log_socketcall_op_write_188(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint8_t a1,
  uint64_t a2,
  uint64_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_1(a1);
  iferret_log_write_8(a2);
  iferret_log_write_8(a3);
#endif
}

static inline void iferret_log_syscall_op_write_188(
  iferret_syscall_t *sc,
  uint8_t a1,
  uint64_t a2,
  uint64_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_1(a1);
  iferret_log_write_8(a2);
  iferret_log_write_8(a3);
#endif
}

static inline void iferret_log_sysret_op_write_188(
  iferret_log_op_enum_t op_num,
  uint8_t a1,
  uint64_t a2,
  uint64_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_1(a1);
  iferret_log_write_8(a2);
  iferret_log_write_8(a3);
#endif
}

static inline void iferret_log_op_write_4(
  iferret_log_op_enum_t op_num,
  uint32_t a1)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
}

static inline void iferret_log_info_flow_op_write_4(
  iferret_log_op_enum_t op_num,
  uint32_t a1)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
#endif
}

static inline void iferret_log_socketcall_op_write_4(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
#endif
}

static inline void iferret_log_syscall_op_write_4(
  iferret_syscall_t *sc,
  uint32_t a1)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
#endif
}

static inline void iferret_log_sysret_op_write_4(
  iferret_log_op_enum_t op_num,
  uint32_t a1)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
#endif
}

static inline void iferret_log_op_write_44(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
}

static inline void iferret_log_info_flow_op_write_44(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
#endif
}

static inline void iferret_log_socketcall_op_write_44(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
#endif
}

static inline void iferret_log_syscall_op_write_44(
  iferret_syscall_t *sc,
  uint32_t a1,
  uint32_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
#endif
}

static inline void iferret_log_sysret_op_write_44(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
#endif
}

static inline void iferret_log_op_write_444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
}

static inline void iferret_log_info_flow_op_write_444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_socketcall_op_write_444(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_syscall_op_write_444(
  iferret_syscall_t *sc,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_sysret_op_write_444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_op_write_4444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
}

static inline void iferret_log_info_flow_op_write_4444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_socketcall_op_write_4444(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_syscall_op_write_4444(
  iferret_syscall_t *sc,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_sysret_op_write_4444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_op_write_44444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
}

static inline void iferret_log_info_flow_op_write_44444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_socketcall_op_write_44444(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_syscall_op_write_44444(
  iferret_syscall_t *sc,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_sysret_op_write_44444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_op_write_444444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
}

static inline void iferret_log_info_flow_op_write_444444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
#endif
}

static inline void iferret_log_socketcall_op_write_444444(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
#endif
}

static inline void iferret_log_syscall_op_write_444444(
  iferret_syscall_t *sc,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
#endif
}

static inline void iferret_log_sysret_op_write_444444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
#endif
}

static inline void iferret_log_op_write_444444444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
}

static inline void iferret_log_info_flow_op_write_444444444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
#endif
}

static inline void iferret_log_socketcall_op_write_444444444(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
#endif
}

static inline void iferret_log_syscall_op_write_444444444(
  iferret_syscall_t *sc,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
#endif
}

static inline void iferret_log_sysret_op_write_444444444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
#endif
}

static inline void iferret_log_op_write_4444444444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9,
  uint32_t a10)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
  iferret_log_write_4(a10);
}

static inline void iferret_log_info_flow_op_write_4444444444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9,
  uint32_t a10)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
  iferret_log_write_4(a10);
#endif
}

static inline void iferret_log_socketcall_op_write_4444444444(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9,
  uint32_t a10)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
  iferret_log_write_4(a10);
#endif
}

static inline void iferret_log_syscall_op_write_4444444444(
  iferret_syscall_t *sc,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9,
  uint32_t a10)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
  iferret_log_write_4(a10);
#endif
}

static inline void iferret_log_sysret_op_write_4444444444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9,
  uint32_t a10)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
  iferret_log_write_4(a10);
#endif
}

static inline void iferret_log_op_write_44444444444444444444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9,
  uint32_t a10,
  uint32_t a11,
  uint32_t a12,
  uint32_t a13,
  uint32_t a14,
  uint32_t a15,
  uint32_t a16,
  uint32_t a17,
  uint32_t a18,
  uint32_t a19,
  uint32_t a20)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
  iferret_log_write_4(a10);
  iferret_log_write_4(a11);
  iferret_log_write_4(a12);
  iferret_log_write_4(a13);
  iferret_log_write_4(a14);
  iferret_log_write_4(a15);
  iferret_log_write_4(a16);
  iferret_log_write_4(a17);
  iferret_log_write_4(a18);
  iferret_log_write_4(a19);
  iferret_log_write_4(a20);
}

static inline void iferret_log_info_flow_op_write_44444444444444444444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9,
  uint32_t a10,
  uint32_t a11,
  uint32_t a12,
  uint32_t a13,
  uint32_t a14,
  uint32_t a15,
  uint32_t a16,
  uint32_t a17,
  uint32_t a18,
  uint32_t a19,
  uint32_t a20)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
  iferret_log_write_4(a10);
  iferret_log_write_4(a11);
  iferret_log_write_4(a12);
  iferret_log_write_4(a13);
  iferret_log_write_4(a14);
  iferret_log_write_4(a15);
  iferret_log_write_4(a16);
  iferret_log_write_4(a17);
  iferret_log_write_4(a18);
  iferret_log_write_4(a19);
  iferret_log_write_4(a20);
#endif
}

static inline void iferret_log_socketcall_op_write_44444444444444444444(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9,
  uint32_t a10,
  uint32_t a11,
  uint32_t a12,
  uint32_t a13,
  uint32_t a14,
  uint32_t a15,
  uint32_t a16,
  uint32_t a17,
  uint32_t a18,
  uint32_t a19,
  uint32_t a20)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
  iferret_log_write_4(a10);
  iferret_log_write_4(a11);
  iferret_log_write_4(a12);
  iferret_log_write_4(a13);
  iferret_log_write_4(a14);
  iferret_log_write_4(a15);
  iferret_log_write_4(a16);
  iferret_log_write_4(a17);
  iferret_log_write_4(a18);
  iferret_log_write_4(a19);
  iferret_log_write_4(a20);
#endif
}

static inline void iferret_log_syscall_op_write_44444444444444444444(
  iferret_syscall_t *sc,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9,
  uint32_t a10,
  uint32_t a11,
  uint32_t a12,
  uint32_t a13,
  uint32_t a14,
  uint32_t a15,
  uint32_t a16,
  uint32_t a17,
  uint32_t a18,
  uint32_t a19,
  uint32_t a20)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
  iferret_log_write_4(a10);
  iferret_log_write_4(a11);
  iferret_log_write_4(a12);
  iferret_log_write_4(a13);
  iferret_log_write_4(a14);
  iferret_log_write_4(a15);
  iferret_log_write_4(a16);
  iferret_log_write_4(a17);
  iferret_log_write_4(a18);
  iferret_log_write_4(a19);
  iferret_log_write_4(a20);
#endif
}

static inline void iferret_log_sysret_op_write_44444444444444444444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5,
  uint32_t a6,
  uint32_t a7,
  uint32_t a8,
  uint32_t a9,
  uint32_t a10,
  uint32_t a11,
  uint32_t a12,
  uint32_t a13,
  uint32_t a14,
  uint32_t a15,
  uint32_t a16,
  uint32_t a17,
  uint32_t a18,
  uint32_t a19,
  uint32_t a20)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
  iferret_log_write_4(a6);
  iferret_log_write_4(a7);
  iferret_log_write_4(a8);
  iferret_log_write_4(a9);
  iferret_log_write_4(a10);
  iferret_log_write_4(a11);
  iferret_log_write_4(a12);
  iferret_log_write_4(a13);
  iferret_log_write_4(a14);
  iferret_log_write_4(a15);
  iferret_log_write_4(a16);
  iferret_log_write_4(a17);
  iferret_log_write_4(a18);
  iferret_log_write_4(a19);
  iferret_log_write_4(a20);
#endif
}

static inline void iferret_log_op_write_44s(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  char * a3)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_s(a3);
}

static inline void iferret_log_info_flow_op_write_44s(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  char * a3)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_s(a3);
#endif
}

static inline void iferret_log_socketcall_op_write_44s(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  char * a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_s(a3);
#endif
}

static inline void iferret_log_syscall_op_write_44s(
  iferret_syscall_t *sc,
  uint32_t a1,
  uint32_t a2,
  char * a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_s(a3);
#endif
}

static inline void iferret_log_sysret_op_write_44s(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  uint32_t a2,
  char * a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_4(a2);
  iferret_log_write_s(a3);
#endif
}

static inline void iferret_log_op_write_4s(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
}

static inline void iferret_log_info_flow_op_write_4s(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
#endif
}

static inline void iferret_log_socketcall_op_write_4s(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
#endif
}

static inline void iferret_log_syscall_op_write_4s(
  iferret_syscall_t *sc,
  uint32_t a1,
  char * a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
#endif
}

static inline void iferret_log_sysret_op_write_4s(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
#endif
}

static inline void iferret_log_op_write_4s4(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
}

static inline void iferret_log_info_flow_op_write_4s4(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_socketcall_op_write_4s4(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_syscall_op_write_4s4(
  iferret_syscall_t *sc,
  uint32_t a1,
  char * a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_sysret_op_write_4s4(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_op_write_4s44(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  uint32_t a4)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
}

static inline void iferret_log_info_flow_op_write_4s44(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_socketcall_op_write_4s44(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_syscall_op_write_4s44(
  iferret_syscall_t *sc,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_sysret_op_write_4s44(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_op_write_4s444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
}

static inline void iferret_log_info_flow_op_write_4s444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_socketcall_op_write_4s444(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_syscall_op_write_4s444(
  iferret_syscall_t *sc,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_sysret_op_write_4s444(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_op_write_4s4s(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  char * a4)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_s(a4);
}

static inline void iferret_log_info_flow_op_write_4s4s(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  char * a4)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_s(a4);
#endif
}

static inline void iferret_log_socketcall_op_write_4s4s(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  char * a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_s(a4);
#endif
}

static inline void iferret_log_syscall_op_write_4s4s(
  iferret_syscall_t *sc,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  char * a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_s(a4);
#endif
}

static inline void iferret_log_sysret_op_write_4s4s(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  char * a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_s(a4);
#endif
}

static inline void iferret_log_op_write_4s4s4(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  char * a4,
  uint32_t a5)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_s(a4);
  iferret_log_write_4(a5);
}

static inline void iferret_log_info_flow_op_write_4s4s4(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  char * a4,
  uint32_t a5)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_s(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_socketcall_op_write_4s4s4(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  char * a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_s(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_syscall_op_write_4s4s4(
  iferret_syscall_t *sc,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  char * a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_s(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_sysret_op_write_4s4s4(
  iferret_log_op_enum_t op_num,
  uint32_t a1,
  char * a2,
  uint32_t a3,
  char * a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_4(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_s(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_op_write_8(
  iferret_log_op_enum_t op_num,
  uint64_t a1)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
}

static inline void iferret_log_info_flow_op_write_8(
  iferret_log_op_enum_t op_num,
  uint64_t a1)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
#endif
}

static inline void iferret_log_socketcall_op_write_8(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint64_t a1)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_8(a1);
#endif
}

static inline void iferret_log_syscall_op_write_8(
  iferret_syscall_t *sc,
  uint64_t a1)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_8(a1);
#endif
}

static inline void iferret_log_sysret_op_write_8(
  iferret_log_op_enum_t op_num,
  uint64_t a1)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
#endif
}

static inline void iferret_log_op_write_81(
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint8_t a2)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
  iferret_log_write_1(a2);
}

static inline void iferret_log_info_flow_op_write_81(
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint8_t a2)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
  iferret_log_write_1(a2);
#endif
}

static inline void iferret_log_socketcall_op_write_81(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint8_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_8(a1);
  iferret_log_write_1(a2);
#endif
}

static inline void iferret_log_syscall_op_write_81(
  iferret_syscall_t *sc,
  uint64_t a1,
  uint8_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_8(a1);
  iferret_log_write_1(a2);
#endif
}

static inline void iferret_log_sysret_op_write_81(
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint8_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
  iferret_log_write_1(a2);
#endif
}

static inline void iferret_log_op_write_84(
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint32_t a2)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
  iferret_log_write_4(a2);
}

static inline void iferret_log_info_flow_op_write_84(
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint32_t a2)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
  iferret_log_write_4(a2);
#endif
}

static inline void iferret_log_socketcall_op_write_84(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint32_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_8(a1);
  iferret_log_write_4(a2);
#endif
}

static inline void iferret_log_syscall_op_write_84(
  iferret_syscall_t *sc,
  uint64_t a1,
  uint32_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_8(a1);
  iferret_log_write_4(a2);
#endif
}

static inline void iferret_log_sysret_op_write_84(
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint32_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
  iferret_log_write_4(a2);
#endif
}

static inline void iferret_log_op_write_884(
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint64_t a2,
  uint32_t a3)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
  iferret_log_write_8(a2);
  iferret_log_write_4(a3);
}

static inline void iferret_log_info_flow_op_write_884(
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint64_t a2,
  uint32_t a3)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
  iferret_log_write_8(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_socketcall_op_write_884(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint64_t a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_8(a1);
  iferret_log_write_8(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_syscall_op_write_884(
  iferret_syscall_t *sc,
  uint64_t a1,
  uint64_t a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_8(a1);
  iferret_log_write_8(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_sysret_op_write_884(
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint64_t a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
  iferret_log_write_8(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_op_write_8844(
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint64_t a2,
  uint32_t a3,
  uint32_t a4)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
  iferret_log_write_8(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
}

static inline void iferret_log_info_flow_op_write_8844(
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint64_t a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
  iferret_log_write_8(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_socketcall_op_write_8844(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint64_t a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_8(a1);
  iferret_log_write_8(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_syscall_op_write_8844(
  iferret_syscall_t *sc,
  uint64_t a1,
  uint64_t a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_8(a1);
  iferret_log_write_8(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_sysret_op_write_8844(
  iferret_log_op_enum_t op_num,
  uint64_t a1,
  uint64_t a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_8(a1);
  iferret_log_write_8(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_op_write_s(
  iferret_log_op_enum_t op_num,
  char * a1)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
}

static inline void iferret_log_info_flow_op_write_s(
  iferret_log_op_enum_t op_num,
  char * a1)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
#endif
}

static inline void iferret_log_socketcall_op_write_s(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  char * a1)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
#endif
}

static inline void iferret_log_syscall_op_write_s(
  iferret_syscall_t *sc,
  char * a1)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
#endif
}

static inline void iferret_log_sysret_op_write_s(
  iferret_log_op_enum_t op_num,
  char * a1)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
#endif
}

static inline void iferret_log_op_write_s4(
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
}

static inline void iferret_log_info_flow_op_write_s4(
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
#endif
}

static inline void iferret_log_socketcall_op_write_s4(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
#endif
}

static inline void iferret_log_syscall_op_write_s4(
  iferret_syscall_t *sc,
  char * a1,
  uint32_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
#endif
}

static inline void iferret_log_sysret_op_write_s4(
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
#endif
}

static inline void iferret_log_op_write_s44(
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2,
  uint32_t a3)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
}

static inline void iferret_log_info_flow_op_write_s44(
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2,
  uint32_t a3)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_socketcall_op_write_s44(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_syscall_op_write_s44(
  iferret_syscall_t *sc,
  char * a1,
  uint32_t a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_sysret_op_write_s44(
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_op_write_s444(
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
}

static inline void iferret_log_info_flow_op_write_s444(
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_socketcall_op_write_s444(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_syscall_op_write_s444(
  iferret_syscall_t *sc,
  char * a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_sysret_op_write_s444(
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_op_write_s4s(
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2,
  char * a3)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_s(a3);
}

static inline void iferret_log_info_flow_op_write_s4s(
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2,
  char * a3)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_s(a3);
#endif
}

static inline void iferret_log_socketcall_op_write_s4s(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2,
  char * a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_s(a3);
#endif
}

static inline void iferret_log_syscall_op_write_s4s(
  iferret_syscall_t *sc,
  char * a1,
  uint32_t a2,
  char * a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_s(a3);
#endif
}

static inline void iferret_log_sysret_op_write_s4s(
  iferret_log_op_enum_t op_num,
  char * a1,
  uint32_t a2,
  char * a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_4(a2);
  iferret_log_write_s(a3);
#endif
}

static inline void iferret_log_op_write_ss(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
}

static inline void iferret_log_info_flow_op_write_ss(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
#endif
}

static inline void iferret_log_socketcall_op_write_ss(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
#endif
}

static inline void iferret_log_syscall_op_write_ss(
  iferret_syscall_t *sc,
  char * a1,
  char * a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
#endif
}

static inline void iferret_log_sysret_op_write_ss(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
#endif
}

static inline void iferret_log_op_write_ss4(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  uint32_t a3)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
}

static inline void iferret_log_info_flow_op_write_ss4(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  uint32_t a3)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_socketcall_op_write_ss4(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_syscall_op_write_ss4(
  iferret_syscall_t *sc,
  char * a1,
  char * a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_sysret_op_write_ss4(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  uint32_t a3)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
#endif
}

static inline void iferret_log_op_write_ss44(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  uint32_t a3,
  uint32_t a4)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
}

static inline void iferret_log_info_flow_op_write_ss44(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_socketcall_op_write_ss44(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_syscall_op_write_ss44(
  iferret_syscall_t *sc,
  char * a1,
  char * a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_sysret_op_write_ss44(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  uint32_t a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_op_write_ss444(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
}

static inline void iferret_log_info_flow_op_write_ss444(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_socketcall_op_write_ss444(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_syscall_op_write_ss444(
  iferret_syscall_t *sc,
  char * a1,
  char * a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_sysret_op_write_ss444(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  uint32_t a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_4(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_op_write_sss4(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  char * a3,
  uint32_t a4)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_s(a3);
  iferret_log_write_4(a4);
}

static inline void iferret_log_info_flow_op_write_sss4(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  char * a3,
  uint32_t a4)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_s(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_socketcall_op_write_sss4(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  char * a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_s(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_syscall_op_write_sss4(
  iferret_syscall_t *sc,
  char * a1,
  char * a2,
  char * a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_s(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_sysret_op_write_sss4(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  char * a3,
  uint32_t a4)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_s(a3);
  iferret_log_write_4(a4);
#endif
}

static inline void iferret_log_op_write_sss44(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  char * a3,
  uint32_t a4,
  uint32_t a5)
{
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_s(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
}

static inline void iferret_log_info_flow_op_write_sss44(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  char * a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_INFO_FLOW 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_s(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_socketcall_op_write_sss44(
  iferret_syscall_t *sc,
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  char * a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_s(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_syscall_op_write_sss44(
  iferret_syscall_t *sc,
  char * a1,
  char * a2,
  char * a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(sc->op_num);
  iferret_log_syscall_commoner(sc);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_s(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

static inline void iferret_log_sysret_op_write_sss44(
  iferret_log_op_enum_t op_num,
  char * a1,
  char * a2,
  char * a3,
  uint32_t a4,
  uint32_t a5)
{
#ifdef IFERRET_SYSCALL 
  iferret_log_op_write_prologue(op_num);
  iferret_log_write_s(a1);
  iferret_log_write_s(a2);
  iferret_log_write_s(a3);
  iferret_log_write_4(a4);
  iferret_log_write_4(a5);
#endif
}

